### PR TITLE
Change throw Error to console.warn

### LINKED ISSUE #2773: Replace throw Error with console.warn for better error handling
### Which package has an issue?

@yamada-ui/use-breakpoint

### Package Version

1.5.0

### Description

I will remove throw Error and instead change the code to use console.warn as shown below.

### As-is
```tsx
export const getBreakpointValue =
  <T extends any>(values: ResponsiveObject<T> = {}) =>
  (theme: StyledTheme, breakpoint: Theme["breakpoints"]): T => {
    if (!theme) throw Error("getBreakpointValue: `theme` is undefined.")

    const breakpoints = theme.__breakpoints?.keys

    if (!breakpoints)
      throw Error("getBreakpointValue: `breakpoints` is undefined.")

    const currentIndex = breakpoints.indexOf(breakpoint)

    for (let i = currentIndex; 0 < i; i--) {
      const nextBreakpoint = breakpoints[i]

      if (values.hasOwnProperty(nextBreakpoint)) {
        return values[nextBreakpoint] as T
      }
    }

    return values.base as T
  }
```

### To-be
```tsx
export const getBreakpointValue =
  <T extends any>(values: ResponsiveObject<T> = {}) =>
  (theme: StyledTheme, breakpoint: Theme["breakpoints"]): T => {
    if (!theme) console.warn("getBreakpointValue: `theme` is undefined.")

    const breakpoints = theme.__breakpoints?.keys

    if (!breakpoints)
      console.warn("getBreakpointValue: `breakpoints` is undefined.")

    const currentIndex = breakpoints.indexOf(breakpoint)

    for (let i = currentIndex; 0 < i; i--) {
      const nextBreakpoint = breakpoints[i]

      if (values.hasOwnProperty(nextBreakpoint)) {
        return values[nextBreakpoint] as T
      }
    }

    return values.base as T
  }
```

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by kaehehehe**
Closes #2773

## Description

I have removed throw Error and changed the code to use console.warn instead.

### CODE REVIEW

**Comment by kaehehehe** [comment]
Should I remove the tests related to throw Error? @hirotomoyamada 
스크린샷 2024-09-19 21 37 46

**Review by uraaaa24 — COMMENTED** [review]
Since you are making a modification to not throw the error, I am wondering if the test needs a similar modification.
It looks like the following.

```diff ts
  test("throws an error if breakpoints are undefined", () => {
    const theme = {} as StyledTheme
-   let error: Error | undefined
+   const consoleWarnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});

-   try {
-     renderHook(() => getBreakpointValue({ base: "md" })(theme, "base"), {
-       withProvider: false,
-     })
-   } catch (e) {
-     if (e instanceof Error) error = e
-   }
+   renderHook(() => getBreakpointValue({ base: "md" })(theme, "base"), {
+     withProvider: false,
+   })

-   expect(error).toBeDefined()
-   expect(error?.message).toBe(
+   expect(consoleWarnSpy).toHaveBeenCalledWith(
      "getBreakpointValue: `breakpoints` is undefined.",
    )
  })
```

**Comment by kaehehehe** [comment]
Fixed! But the test still does not pass. 😭

File: packages/hooks/use-breakpoint/src/index.ts [hunk 1]
```diff
@@ -150,12 +158,16 @@ export const useBreakpointValue = <T>(values: ResponsiveObject<T>): T => {
 export const getBreakpointValue =
   <T>(values: ResponsiveObject<T> = {}) =>
   (theme: StyledTheme, breakpoint: Theme["breakpoints"]): T => {
-    if (!theme) throw Error("getBreakpointValue: `theme` is undefined.")
+    if (!theme) {
+      console.warn("getBreakpointValue: `theme` is undefined.")
+    }
 
-    const breakpoints = theme.__breakpoints?.keys
+    let breakpoints = theme.__breakpoints?.keys
```
Comment (uraaaa24) [inline packages/hooks/use-breakpoint/src/index.ts:165]: The modification allows processing to proceed even if theme is undefined, resulting in an error if theme.__breakpoints or theme.__breakpoints.keys is undefined.
I think you should include optional chaining.
`let breakpoints = theme?.__breakpoints?.keys`.

**Review by uraaaa24 — COMMENTED** [review]
I think I may have found the cause of the error in the test.
I left a comment, please check it out!

**Comment by hirotomoyamada** [comment]
@kaehehehe 

> Should I remove the tests related to throw Error?

The test is unnecessary. Delete it or test in another way.

File: docs/components/layouts/header.tsx
Comment (hirotomoyamada) [inline docs/components/layouts/header.tsx:1]: This file does not need to be changed. Please revert to the original.

File: packages/hooks/use-value/src/index.ts
Comment (hirotomoyamada) [inline packages/hooks/use-value/src/index.ts:1]: This file does not need to be changed. Please revert to the original.

File: .changeset/honest-planets-jump.md
Comment (hirotomoyamada) [inline .changeset/honest-planets-jump.md:1]: Only `"@yamada-ui/use-breakpoint"` has been changed. Other than that, please revert to the original.

File: packages/hooks/use-breakpoint/src/index.ts [hunk 2]
```diff
@@ -207,7 +225,13 @@ export const useUpdateBreakpointEffect = (
   callback: (breakpoint: Theme["breakpoints"]) => void,
   deps: DependencyList,
 ) => {
-  const breakpoint = useBreakpoint()
+  const breakpoint = useBreakpoint() as
```
Comment (hirotomoyamada) [inline packages/hooks/use-breakpoint/src/index.ts:228]: This line does not need to be changed. Please change it back to the original.

File: packages/hooks/use-breakpoint/src/index.ts [hunk 3]
```diff
@@ -190,7 +202,13 @@ export const useBreakpointEffect = (
...
```
Comment (hirotomoyamada) [inline packages/hooks/use-breakpoint/src/index.ts:205]: This line does not need to be changed. Please change it back to the original.

File: packages/hooks/use-breakpoint/src/index.ts [hunk 4]
```diff
@@ -139,7 +141,13 @@ export const useBreakpoint = () => {
  */
 export const useBreakpointValue = <T>(values: ResponsiveObject<T>): T => {
   const { theme } = useTheme()
-  const breakpoint = useBreakpoint()
+  const breakpoint = useBreakpoint() as
```
Comment (hirotomoyamada) [inline packages/hooks/use-breakpoint/src/index.ts:144]: This line does not need to be changed. Please change it back to the original.

File: packages/hooks/use-breakpoint/src/index.ts
Comment (hirotomoyamada) [inline packages/hooks/use-breakpoint/src/index.ts:1]: Do not use `return` before `useMemo` or `useEffect`. As an approach, have a `hasBreakpoint` and interrupt processing of each logic with that flag, so that `useBreakpoint` returns `"base"`.

**Comment by kaehehehe** [comment]
fixed! @hirotomoyamada @uraaaa24

**Review by uraaaa24 — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]
