### PR TITLE
Calendar day and root prop getters now merge user props with mergeProps

### LINKED ISSUE #6809: bug(calendar): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/calendar/use-calendar.ts:653 — outer getter`
- `packages/react/src/components/calendar/use-calendar.ts:1059 — inner getter (uses `mergeRefs(ref, cellRef, register)`)`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6809

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

useCalendar getRootProps and useCalendarDay getDayProps now use mergeProps for correct className, style, ref, and event merging.

## Is this a breaking change (Yes/No):

No

## Additional Information

Tests: pnpm react test:jsdom --run src/components/calendar/calendar.test.tsx

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/calendar/use-calendar.ts [hunk 1]
```diff
@@ -1030,40 +1027,45 @@ export const useCalendarDay = ({ value, ...rest }: UseCalendarDayProps) => {
...
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, cellRef, outside ? null : register),
+          onBlur,
+          onClick,
+          onFocus: (ev) => ev.preventDefault(),
+          onKeyDown,
+        },
+      )()
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/calendar/use-calendar.ts:1068]: **Issue:** CLAUDE.md mandates "Tests are required: Always write tests when fixing bugs or adding new features." This PR fixes an observable bug — in the previous `getDayProps`, the raw spread placed `...rest, ...props, ref:..., onBlur: handlerAll(props.onBlur, onBlur), ...` in that order, so `rest.ref`, `rest.onBlur`, `rest.onClick`, `rest.onKeyDown`, `rest.onFocus` and anything like `rest.className`/`rest.style` coming from `useCalendarDay({ value, ...rest })` were silently overwritten or ignored (the `CalendarDay` component passes user props straight into `useCalendarDay(props)` in `calendar.tsx:591`, so this is exactly the consumer path). After the switch to `mergeProps(defaults, rest, props, { ref: mergeRefs(...), onBlur, onClick, onFocus, onKeyDown })()`, those user values now merge with the hook's internals. No test in `calendar.test.tsx` asserts this new merging behavior, so a future refactor could re-introduce the bug without any failing test. The same applies to `getRootProps` at line 650-654 when consumers invoke it with their own props.

**Fix:** Add unit tests in `packages/react/src/components/calendar/calendar.test.tsx` that render `<Calendar.Root>` / `<Calendar.Day>` (or directly exercise `useCalendar`/`useCalendarDay`) with user-supplied `className`, `style`, `ref`, and `onClick`/`onBlur`/`onFocus`/`onKeyDown`, and verify that (a) the user's `ref` receives the element alongside the internal refs, (b) user `className`/`style` are merged with the hook's, and (c) user event handlers are invoked in addition to the hook's internal handlers (e.g. clicking selects the date and also calls the user's `onClick`).

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: CLAUDE.md mandates "Tests are required: Always write tests when fixing bugs or adding new features." This PR fixes an observable bug — in the previous `getDayProps`, the raw spread placed `...rest, ...props, ref:..., onBlur: handlerAll(props.onBlur, onBlur), ...` in that order, so `rest.ref`, `rest.onBlur`, `rest.onClick`, `rest.onKeyDown`, `rest.onFocus` and anything like `rest.className`/`rest.style` coming from `useCalendarDay({ value, ...rest })` were silently overwritten or ignored (the `CalendarDay` component passes user props straight into `useCalendarDay(props)` in `calendar.tsx:591`, so this is exactly the consumer path). After the switch to `mergeProps(defaults, rest, props, { ref: mergeRefs(...), onBlur, onClick, onFocus, onKeyDown })()`, those user values now merge with the hook's internals. No test in `calendar.test.tsx` asserts this new merging behavior, so a future refactor could re-introduce the bug without any failing test. The same applies to `getRootProps` at line 650-654 when consumers invoke it with their own props.

File: packages/react/src/components/calendar/use-calendar.ts [hunk 2]
```diff
@@ -1030,40 +1027,45 @@ export const useCalendarDay = ({ value, ...rest }: UseCalendarDayProps) => {
...
+          "data-start": dataAttr(startValue),
+          "data-today": dataAttr(today),
+          "data-value": dayjs(value).format("YYYY-MM-DD"),
+          "data-weekend": dataAttr(weekend),
+          tabIndex: -1,
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, cellRef, outside ? null : register),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/calendar/use-calendar.ts]: **Issue:** `getDayProps` now passes `props` to `mergeProps` and also builds `ref` with `mergeRefs(ref, cellRef, outside ? null : register)`. Because `mergeProps` already merges `ref` across args, a `ref` passed via `getDayProps({ ref })` is composed twice and gets assigned twice, which can trigger duplicate callback-ref side effects.

**Fix:** Do not include the incoming `ref` in the final internal ref composition. Use `ref: mergeRefs(cellRef, outside ? null : register)` and let `mergeProps(..., rest, props, ...)` merge caller refs once.

File: .changeset/calendar-mergeprops-6809.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Merge `getRootProps` and `getDayProps` in the calendar hooks with `mergeProps` so user `className`, `style`, `ref`, and event handlers combine correctly with hook defaults.
```
Comment (codex-for-yamada-ui) [inline .changeset/calendar-mergeprops-6809.md:5]: **Issue:** The PR changes runtime merge behavior for `getRootProps`/`getDayProps` (`className`, `style`, `ref`, event handlers), but there is no test change in the diff to validate these new merge semantics.

**Fix:** Add regression tests in `packages/react/src/components/calendar/calendar.test.tsx` that assert merged `className`/`style`, composed event handlers, and single ref composition for both `Calendar.Root` and day props paths.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `getDayProps` now passes `props` to `mergeProps` and also builds `ref` with `mergeRefs(ref, cellRef, outside ? null : register)`. Because `mergeProps` already merges `ref` across args, a `ref` passed via `getDayProps({ ref })` is composed twice and gets assigned twice, which can trigger duplicate callback-ref side effects.
- テスト: The PR changes runtime merge behavior for `getRootProps`/`getDayProps` (`className`, `style`, `ref`, event handlers), but there is no test change in the diff to validate these new merge semantics.

File: packages/react/src/components/calendar/use-calendar.ts (hunk 1 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/calendar/use-calendar.ts:1068]: **Issue:** The PR only changes the calendar hooks and a changeset; it adds or updates no tests. The new `mergeProps` composition path for `getDayProps` (and the sibling change to `getRootProps` at `use-calendar.ts:650-652`) is therefore not regression-tested under this diff, and user overrides for `className` / `style` / `ref` / event handlers are not verified at the test layer despite being the behavior this PR targets.

**Fix:** Add tests (e.g. extend `packages/react/src/components/calendar/calendar.test.tsx` or a dedicated `use-calendar` test) that render `Calendar` (or a minimal harness that calls `getDayProps` / `getRootProps`) with user `className` and at least one user event handler (and optionally a `ref` mock) and assert that host props merge with hook output as intended—for example, that multiple `className` values appear on the same node, or that both the user and internal handlers run when a day is interacted with.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The PR only changes the calendar hooks and a changeset; it adds or updates no tests. The new `mergeProps` composition path for `getDayProps` (and the sibling change to `getRootProps` at `use-calendar.ts:650-652`) is therefore not regression-tested under this diff, and user overrides for `className` / `style` / `ref` / event handlers are not verified at the test layer despite being the behavior this PR targets.

File: packages/react/src/components/calendar/use-calendar.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/calendar/use-calendar.ts:1068]: Fixed.

File: .changeset/calendar-mergeprops-6809.md (hunk 3 above)
Comment (codex-for-yamada-ui) [reply .changeset/calendar-mergeprops-6809.md:5]: Fixed.

File: packages/react/src/components/calendar/use-calendar.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/calendar/use-calendar.ts]: Fixed.

File: packages/react/src/components/calendar/use-calendar.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/calendar/use-calendar.ts:1068]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
