### PR TITLE
fix(resizable): use mergeProps for prop getters

### LINKED ISSUE #6827: bug(resizable): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/resizable/use-resizable.ts:64 — getter (uses `mergeRefs(props.groupRef, groupRef, controlRef)`)`
- `packages/react/src/components/resizable/use-resizable.ts:108 — getter (uses `mergeRefs(props.panelRef, panelRef, controlRef)`)`
- `packages/react/src/components/resizable/use-resizable.ts:165 — getter`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Note: `useResizable` uses non-standard ref keys (`groupRef`, `panelRef`). `mergeProps` only merges the standard `ref` field, so these custom ref keys may need to be merged manually with `mergeRefs(...)` outside of (or after) `mergeProps`.

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6827

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Uses `mergeProps` for resizable prop getters; keeps explicit `mergeRefs`, `fnAll`, and root `style` where the library needs fixed behavior.

## Current behavior (updates)

Raw spreads merging hook and consumer props.

## New behavior

Consistent merging via `mergeProps` plus explicit refs and layout callbacks.

## Is this a breaking change (Yes/No):

No

## Additional Information

None.

### CODE REVIEW

File: packages/react/src/components/resizable/use-resizable.ts [hunk 1]
```diff
@@ -156,21 +160,25 @@ export const useResizableTrigger = ({
...
+        {
+          "aria-disabled": ariaAttr(trulyDisabled),
+          "aria-orientation": orientation,
+          "data-disabled": dataAttr(trulyDisabled),
+          disabled: trulyDisabled,
+          tabIndex: trulyDisabled ? -1 : 0,
+        },
+        props,
+        rest,
+        { onDoubleClick },
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:174]: **Issue:** The `mergeProps` argument order in `getTriggerProps` is `(baseProps, props, rest, { onDoubleClick })`, which places `rest` AFTER `props`. In `mergeProps`, later args win for plain (non-className/style/event/ref) keys, so hook-level `rest` now overrides consumer-supplied `props` for keys like `id`, `role`, `tabIndex`, custom `data-*`/`aria-*` not in the base object, etc. This both (a) reverses the original `...rest, ...props` precedence (where `props` won) and (b) is inconsistent with the sibling getters in this file (`getRootProps` uses `(base, rest, props)` and `getItemProps` uses `(rest, props)`). It also deviates from the pattern called out in the linked issue #6827 and the carousel reference (`rest, props, { internalHandlers }`).

**Fix:** Swap the order to `mergeProps({ "aria-disabled": ..., "aria-orientation": ..., "data-disabled": ..., disabled: trulyDisabled, tabIndex: ... }, rest, props, { onDoubleClick })()` so consumer-supplied props win over hook-level props, matching the other two getters and the issue-specified pattern.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:174]: **Issue:** This is a fix that changes prop-merging semantics (className/style now merge instead of override, events now chain, rest/props precedence in `getTriggerProps` changed), but no tests were added. `CLAUDE.md` requires tests for bug fixes, and `resizable.test.tsx` has no coverage asserting merge behavior for `getRootProps` / `getItemProps` / `getTriggerProps` (className, style, refs, event handler chaining, consumer-vs-hook precedence).

**Fix:** Add regression tests in `packages/react/src/components/resizable/resizable.test.tsx` that render with both hook-level and consumer-level `className`, `style`, `ref`, and event handlers, and assert they are merged/chained (not overwritten) and that consumer props take precedence over hook props for plain keys — especially for the `<Resizable.Trigger>` path to pin down the order regression called out in Finding 1.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness / Consistency (regression): The `mergeProps` argument order in `getTriggerProps` is `(baseProps, props, rest, { onDoubleClick })`, which places `rest` AFTER `props`. In `mergeProps`, later args win for plain (non-className/style/event/ref) keys, so hook-level `rest` now overrides consumer-supplied `props` for keys like `id`, `role`, `tabIndex`, custom `data-*`/`aria-*` not in the base object, etc. This both (a) reverses the original `...rest, ...props` precedence (where `props` won) and (b) is inconsistent with the sibling getters in this file (`getRootProps` uses `(base, rest, props)` and `getItemProps` uses `(rest, props)`). It also deviates from the pattern called out in the linked issue #6827 and the carousel reference (`rest, props, { internalHandlers }`).
- Tests: This is a fix that changes prop-merging semantics (className/style now merge instead of override, events now chain, rest/props precedence in `getTriggerProps` changed), but no tests were added. `CLAUDE.md` requires tests for bug fixes, and `resizable.test.tsx` has no coverage asserting merge behavior for `getRootProps` / `getItemProps` / `getTriggerProps` (className, style, refs, event handler chaining, consumer-vs-hook precedence).

File: packages/react/src/components/resizable/use-resizable.ts [hunk 2]
```diff
@@ -156,21 +160,25 @@ export const useResizableTrigger = ({
...
+      const merged = mergeProps(
+        {
+          "aria-disabled": ariaAttr(trulyDisabled),
+          "aria-orientation": orientation,
+          "data-disabled": dataAttr(trulyDisabled),
+          disabled: trulyDisabled,
+          tabIndex: trulyDisabled ? -1 : 0,
+        },
+        props,
+        rest,
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:173]: **Issue:** `getTriggerProps` now calls `mergeProps(..., props, rest, ...)`, so non-merged keys (for example `id`, `role`, `data-*`) from hook-level `rest` overwrite per-call `props`. This reverses the previous `...rest, ...props` precedence and is inconsistent with `getRootProps`/`getItemProps`, so callers can no longer reliably override trigger props at call time.

**Fix:** Keep base precedence as `rest -> props` and handle the double-click chain explicitly, e.g. merge with `mergeProps(base, rest, props)()` and set `onDoubleClick` with `handlerAll(props.onDoubleClick, rest.onDoubleClick, onDoubleClick)` (or equivalent) so call-site overrides still work.

File: .changeset/resizable-merge-props.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Use `mergeProps` in resizable hooks `getRootProps`, `getItemProps`, and `getTriggerProps` for correct prop merging.
```
Comment (codex-for-yamada-ui) [inline .changeset/resizable-merge-props.md:5]: **Issue:** The PR changes prop-merging behavior for three public prop getters (`getRootProps`, `getItemProps`, `getTriggerProps`) but adds no test coverage for the new merge semantics (class/style/event/ref precedence). The current resizable tests do not validate these merge contracts, so regressions like the precedence reversal above are not caught.

**Fix:** Add focused tests for these three getters that assert precedence and handler composition (including call-time props overriding hook-level props for `getTriggerProps`).

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `getTriggerProps` now calls `mergeProps(..., props, rest, ...)`, so non-merged keys (for example `id`, `role`, `data-*`) from hook-level `rest` overwrite per-call `props`. This reverses the previous `...rest, ...props` precedence and is inconsistent with `getRootProps`/`getItemProps`, so callers can no longer reliably override trigger props at call time.
- テスト: The PR changes prop-merging behavior for three public prop getters (`getRootProps`, `getItemProps`, `getTriggerProps`) but adds no test coverage for the new merge semantics (class/style/event/ref precedence). The current resizable tests do not validate these merge contracts, so regressions like the precedence reversal above are not caught.

File: packages/react/src/components/resizable/use-resizable.ts [hunk 4]
```diff
@@ -156,21 +160,25 @@ export const useResizableTrigger = ({
...
+        { onDoubleClick },
+      )()
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:175]: **Issue:** `mergeProps` is called as `mergeProps(base, props, rest, { onDoubleClick })`, so later objects win for ordinary keys. That makes hook `rest` override the `props` argument to the `PropGetter`. Previously the object literal used `...rest` then `...props`, so call-side `props` won. Anyone using `useResizableTrigger` and `getTriggerProps(overrides)` with the same key on both hook input and the getter argument (e.g. `aria-*`, `id`, `data-*`) now gets the opposite winner; this is a backward-incompatible behavior change relative to the pre-PR spread order.

**Fix:** Restore spread precedence for non-handler props while keeping composed handlers—for example `mergeProps(base, rest, props, { onDoubleClick })()` for static props so `props` beats `rest`, and verify `onDoubleClick` composition still matches `handlerAll(props.onDoubleClick, rest.onDoubleClick, onDoubleClick)` (split static merge vs. explicit `handlerAll` if one `mergeProps` ordering cannot satisfy both).

File: packages/react/src/components/resizable/use-resizable.ts [hunk 5]
```diff
@@ -104,13 +105,16 @@ export const useResizableItem = ({
...
-    }),
+    (props = {}) => {
+      const merged = mergeProps(rest, props)()
+
+      return {
+        ...merged,
+        elementRef: mergeRefs(props.elementRef, rest.ref),
+        panelRef: mergeRefs(props.panelRef, panelRef, controlRef),
+        onResize: fnAll(props.onResize, rest.onResize),
+      }
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:116]: **Issue:** `getItemProps` now uses `mergeProps(rest, props)()`. `mergeProps` deep-merges `style` via `merge()` and combines `className` with `cx`. The old implementation used `{ ...rest, ...props }`, so a `style` (or `className`) on `props` replaced the entire `rest.style` (`rest.className`) instead of merging with it. Imperative `getItemProps(partial)` therefore changes for overlapping `style` / `className`; default `getItemProps()` usage is unchanged.

**Fix:** If replacement semantics are required, mirror `getRootProps` by taking `style`/`className` from `mergeProps` but then overriding with explicit shallow merges, or call `mergeProps` with `mergeStyle: false` / `mergeClassName: false` and apply the previous spread rules for those keys only.

File: packages/react/src/components/resizable/use-resizable.ts [hunk 6]
```diff
@@ -58,22 +58,23 @@ export const useResizable = ({
...
+          height: undefined,
+          width: undefined,
+          ...rest.style,
+          ...props.style,
+        },
+        elementRef: mergeRefs(props.elementRef, rest.ref),
+        groupRef: mergeRefs(props.groupRef, groupRef, controlRef),
+        onLayoutChange: fnAll(props.onLayoutChange, rest.onLayoutChange),
+        onLayoutChanged: fnAll(props.onLayoutChanged, rest.onLayoutChanged),
+      }
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:76]: **Issue:** `getRootProps` spreads `...merged` from `mergeProps({ disabled, orientation }, rest, props)()`, so `className` is produced with `cx` across `rest` and `props`. Previously `...rest, ...props` meant the getter argument’s `className` fully replaced the hook’s. Imperative `getRootProps(overrides)` with both sides setting `className` no longer matches the old last-wins behavior (while `style` is still rebuilt with the same shallow `{ ...rest.style, ...props.style }` as before).

**Fix:** After `mergeProps`, override `className` with the previous precedence (e.g. `props.className ?? rest.className` or explicit `cx` only when you intend composition), or document and test the new `cx` behavior as an intentional breaking change.

File: packages/react/src/components/resizable/use-resizable.ts [hunk 7]
```diff
@@ -156,21 +160,25 @@ export const useResizableTrigger = ({
...
+        },
+        props,
+        rest,
+        { onDoubleClick },
+      )()
+
+      return {
+        ...merged,
+        elementRef: mergeRefs(props.elementRef, rest.ref),
+      }
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/resizable/use-resizable.ts:180]: **Issue:** The diff changes `PropGetter` merge semantics (precedence, `style`/`className`, and `mergeProps`-based event chaining) but does not add or adjust tests under `resizable.test.tsx` (or elsewhere) to lock in expected precedence or style/className behavior, so regressions in imperative hook usage would not be detected.

**Fix:** Add focused tests for `useResizable` / `useResizableItem` / `useResizableTrigger` that call each `PropGetter` with overlapping keys on hook `rest` vs. getter `props`, including `style`, `className`, and `onDoubleClick`, and assert the intended merge order and handler invocation.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness / Breaking changes: `mergeProps` is called as `mergeProps(base, props, rest, { onDoubleClick })`, so later objects win for ordinary keys. That makes hook `rest` override the `props` argument to the `PropGetter`. Previously the object literal used `...rest` then `...props`, so call-side `props` won. Anyone using `useResizableTrigger` and `getTriggerProps(overrides)` with the same key on both hook input and the getter argument (e.g. `aria-*`, `id`, `data-*`) now gets the opposite winner; this is a backward-incompatible behavior change relative to the pre-PR spread order.
- Correctness / Breaking changes: `getItemProps` now uses `mergeProps(rest, props)()`. `mergeProps` deep-merges `style` via `merge()` and combines `className` with `cx`. The old implementation used `{ ...rest, ...props }`, so a `style` (or `className`) on `props` replaced the entire `rest.style` (`rest.className`) instead of merging with it. Imperative `getItemProps(partial)` therefore changes for overlapping `style` / `className`; default `getItemProps()` usage is unchanged.
- Correctness / Breaking changes / Consistency: `getRootProps` spreads `...merged` from `mergeProps({ disabled, orientation }, rest, props)()`, so `className` is produced with `cx` across `rest` and `props`. Previously `...rest, ...props` meant the getter argument’s `className` fully replaced the hook’s. Imperative `getRootProps(overrides)` with both sides setting `className` no longer matches the old last-wins behavior (while `style` is still rebuilt with the same shallow `{ ...rest.style, ...props.style }` as before).
- Tests: The diff changes `PropGetter` merge semantics (precedence, `style`/`className`, and `mergeProps`-based event chaining) but does not add or adjust tests under `resizable.test.tsx` (or elsewhere) to lock in expected precedence or style/className behavior, so regressions in imperative hook usage would not be detected.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
