### PR TITLE
fix(rating): use mergeProps for getRootProps and getLabelProps

### LINKED ISSUE #6825: bug(rating): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/rating/use-rating.tsx:198 — getter (uses `mergeRefs(ref, rest.ref, rootRef)`)`
- `packages/react/src/components/rating/use-rating.tsx:350 — getter`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6825

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Migrates `useRating` `getRootProps` and `useRatingItem` `getLabelProps` to `mergeProps`.

## Current behavior (updates)

Raw spreads for hook and consumer props.

## New behavior

`mergeProps` merges refs, class names, styles, and events consistently.

## Is this a breaking change (Yes/No):

No

## Additional Information

None.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/rating/use-rating.tsx [hunk 1]
```diff
@@ -187,35 +187,29 @@ export const useRating = (props: UseRatingProps = {}) => {
...
+        eventProps,
+        ariaProps,
+        {
+          id,
+          "aria-label": `${value} Stars`,
+          "aria-readonly": ariaAttr(readOnly),
+          role: "radiogroup",
+        },
+        props,
+        rest,
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx]: **Issue:** In `getRootProps`, `props` (caller-supplied) is placed before `rest` (hook's remaining field props) in the `mergeProps` args. Because `mergeProps` has later args override earlier ones for non-specially-merged fields (anything other than `ref`/`className`/`style`/`css` or event handlers), `rest` now overrides `props` for fields like `aria-label`, `role`, `data-*`, generic `aria-*`, `tabIndex`, `id`, etc. This reverses the original spread order `...rest, ...props` (where caller's props won) and contradicts the pattern recommended by the issue this PR closes (#6825), which explicitly shows `mergeProps({ ... }, rest, props, { internal handlers })()` with `props` as the last consumer-facing arg. Trace example: for `useRating({ "aria-label": "X" })` then `getRootProps({ "aria-label": "Y" })`, the original code produced `"Y"` but the new code produces `"X"`. The PR body claims "No" breaking change, but this is a behavior regression and is the opposite of the intended fix.

**Fix:** Swap the order so `rest` comes before `props`: `mergeProps(dataProps, eventProps, ariaProps, { id, "aria-label": ..., ... }, rest, props, { ref }, { ref: rootRef }, { onMouseEnter, onMouseLeave, onMouseMove, onTouchEnd, onTouchStart })()`. This matches both the original spread precedence and the `use-carousel` pattern cited in #6825.

File: packages/react/src/components/rating/use-rating.tsx [hunk 2]
```diff
@@ -341,21 +335,31 @@ export const useRatingItem = ({
...
+            zIndex: fractionValue !== 1 ? (active ? 1 : -1) : undefined,
+          },
+        },
+      )()
+
+      return {
+        ...merged,
+        onMouseDown: handlerAll(props.onMouseDown, onMouseDown),
+        onTouchStart: handlerAll(props.onTouchStart, onTouchStart),
+      }
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx]: **Issue:** `getLabelProps` mixes `mergeProps` with a post-merge manual override for `onMouseDown`/`onTouchStart`. `mergeProps` is already chaining those handlers from `rest` and `props` (since they are events), but then the return statement overwrites them with `handlerAll(props.onMouseDown, onMouseDown)`, discarding the chain `mergeProps` produced. This is inconsistent with `getRootProps` in the same diff, which correctly appends `{ onMouseEnter, onMouseLeave, onMouseMove, onTouchEnd, onTouchStart }` as the last `mergeProps` arg. The inconsistency makes the merging semantics unclear and also silently drops `rest.onMouseDown`/`rest.onTouchStart` that `mergeProps` would have chained.

**Fix:** Follow the same pattern as `getRootProps`: append `{ onMouseDown, onTouchStart }` as the last `mergeProps` arg and return the merged result directly, e.g. `return mergeProps(dataProps, ariaProps, { htmlFor, "data-active", "data-filled" }, rest, props, { style }, { style: { zIndex: ... } }, { onMouseDown, onTouchStart })()`.

File: packages/react/src/components/rating/use-rating.tsx [hunk 3]
```diff
@@ -187,35 +187,29 @@ export const useRating = (props: UseRatingProps = {}) => {
   }, [])
 
   const getRootProps: PropGetter = useCallback(
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx:189]: **Issue:** The PR changes prop-merging semantics (class names get `cx`'d, styles merged, event handlers including `onBlur`/`onFocus` from `eventProps` chained instead of overwritten) yet no tests are added. `rating.test.tsx` in the adjacent file currently has no coverage for `getRootProps`/`getLabelProps` merge behavior (no assertions on `className` combination, merged `style`, `ref` forwarding, or `onBlur`/`onFocus` chaining). Per the project's Critical Rules in `CLAUDE.md`: "Tests are required: Always write tests when fixing bugs or adding new features." Without tests, the regression in Finding 1 and any future regression in merging semantics will go undetected. (Anchored to the `getRootProps` declaration since the tests live outside this diff in `rating.test.tsx`.)

**Fix:** Add tests that assert (a) caller-supplied `aria-label`/`role` to `getRootProps` win over hook-rest values, (b) `className` from both is combined, (c) `style` objects are deep-merged with the hook's `zIndex`, (d) `onBlur`/`onFocus` provided both via `<Rating>` and via `getRootProps` fire in the correct order, (e) refs from caller, `rest.ref`, and `rootRef` are all attached.

File: .changeset/rating-merge-props.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Use `mergeProps` in `useRating` `getRootProps` and `useRatingItem` `getLabelProps` for correct prop merging.
```
Comment (claude-for-yamada-ui) [inline .changeset/rating-merge-props.md]: **Issue:** The changeset is marked `patch` and phrased as a neutral implementation note ("Use `mergeProps` ... for correct prop merging"), but the change is user-observable: `onBlur`/`onFocus` from `<Rating>` props are now chained with caller-supplied handlers instead of being overwritten, `className` is now concatenated via `cx` instead of replaced, and `style` is now deep-merged instead of spread-replaced. Consumers relying on the previous overwrite semantics will see behavior changes. The PR body also answers "No" to the breaking-change question, but the changeset at minimum should describe these observable semantic changes so release notes accurately reflect them.

**Fix:** Update the changeset body to explicitly describe the semantic changes (e.g., "Consumer-supplied `className`, `style`, refs, and event handlers on `Rating`'s root and label are now correctly merged with the hook's internal values instead of being overwritten"), so downstream users can act on the change.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: In `getRootProps`, `props` (caller-supplied) is placed before `rest` (hook's remaining field props) in the `mergeProps` args. Because `mergeProps` has later args override earlier ones for non-specially-merged fields (anything other than `ref`/`className`/`style`/`css` or event handlers), `rest` now overrides `props` for fields like `aria-label`, `role`, `data-*`, generic `aria-*`, `tabIndex`, `id`, etc. This reverses the original spread order `...rest, ...props` (where caller's props won) and contradicts the pattern recommended by the issue this PR closes (#6825), which explicitly shows `mergeProps({ ... }, rest, props, { internal handlers })()` with `props` as the last consumer-facing arg. Trace example: for `useRating({ "aria-label": "X" })` then `getRootProps({ "aria-label": "Y" })`, the original code produced `"Y"` but the new code produces `"X"`. The PR body claims "No" breaking change, but this is a behavior regression and is the opposite of the intended fix.
- 一貫性: `getLabelProps` mixes `mergeProps` with a post-merge manual override for `onMouseDown`/`onTouchStart`. `mergeProps` is already chaining those handlers from `rest` and `props` (since they are events), but then the return statement overwrites them with `handlerAll(props.onMouseDown, onMouseDown)`, discarding the chain `mergeProps` produced. This is inconsistent with `getRootProps` in the same diff, which correctly appends `{ onMouseEnter, onMouseLeave, onMouseMove, onTouchEnd, onTouchStart }` as the last `mergeProps` arg. The inconsistency makes the merging semantics unclear and also silently drops `rest.onMouseDown`/`rest.onTouchStart` that `mergeProps` would have chained.
- テスト: The PR changes prop-merging semantics (class names get `cx`'d, styles merged, event handlers including `onBlur`/`onFocus` from `eventProps` chained instead of overwritten) yet no tests are added. `rating.test.tsx` in the adjacent file currently has no coverage for `getRootProps`/`getLabelProps` merge behavior (no assertions on `className` combination, merged `style`, `ref` forwarding, or `onBlur`/`onFocus` chaining). Per the project's Critical Rules in `CLAUDE.md`: "Tests are required: Always write tests when fixing bugs or adding new features." Without tests, the regression in Finding 1 and any future regression in merging semantics will go undetected. (Anchored to the `getRootProps` declaration since the tests live outside this diff in `rating.test.tsx`.)
- スコープと規約: The changeset is marked `patch` and phrased as a neutral implementation note ("Use `mergeProps` ... for correct prop merging"), but the change is user-observable: `onBlur`/`onFocus` from `<Rating>` props are now chained with caller-supplied handlers instead of being overwritten, `className` is now concatenated via `cx` instead of replaced, and `style` is now deep-merged instead of spread-replaced. Consumers relying on the previous overwrite semantics will see behavior changes. The PR body also answers "No" to the breaking-change question, but the changeset at minimum should describe these observable semantic changes so release notes accurately reflect them.

File: packages/react/src/components/rating/use-rating.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx]: **Issue:** `mergeProps` now receives `props` before `rest`, so for non-event keys `rest` overrides `props`. This reverses the previous `...rest, ...props` behavior, meaning values passed to `getRootProps(props)` can no longer reliably override hook-level props when both define the same key.

**Fix:** Restore non-event precedence so `props` wins over `rest` (same as before), while explicitly composing root event handlers to preserve the intended handler order (`props` -> `rest` -> internal).

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` now receives `props` before `rest`, so for non-event keys `rest` overrides `props`. This reverses the previous `...rest, ...props` behavior, meaning values passed to `getRootProps(props)` can no longer reliably override hook-level props when both define the same key.

File: packages/react/src/components/rating/use-rating.tsx (hunk 1 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx]: **Issue:** `mergeProps` applies later arguments over earlier ones for normal keys. The previous implementation used `...rest, ...props`, so values from the `getRootProps` argument (`props`) overrode hook-level `rest`. The new call passes `props` before `rest`, so `rest` wins and caller-supplied root props no longer override `useRating`’s remaining props—unlike `getLabelProps` in the same file, which lists `rest` then `props`, and unlike common usage such as `mergeProps(headerProps, props)` in `sidebar.tsx`.

**Fix:** Swap the order to `rest` then `props` (keeping `ref` and internal handler objects after both), e.g. `mergeProps(dataProps, eventProps, ariaProps, { id, … }, rest, props, { ref }, { ref: rootRef }, { onMouseEnter, … })`.

File: packages/react/src/components/rating/use-rating.tsx [hunk 5]
```diff
@@ -341,21 +335,31 @@ export const useRatingItem = ({
...
-      ...props,
-      style: {
-        ...style,
-        zIndex: fractionValue !== 1 ? (active ? 1 : -1) : undefined,
-      },
-      onMouseDown: handlerAll(props.onMouseDown, onMouseDown),
-      onTouchStart: handlerAll(props.onTouchStart, onTouchStart),
-    }),
+    ({ style, ...props } = {}) => {
+      const merged = mergeProps(
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/rating/use-rating.tsx]: **Issue:** The diff only changes runtime merging in `use-rating.tsx` and adds a changeset; it does not add or update tests. The repository requires covering changed behavior for fixes, and the `getRootProps` / `getLabelProps` merge order and `mergeProps` integration are not exercised by new assertions in this PR.

**Fix:** Add tests (for example in `rating.test.tsx` or a dedicated hook test) that assert merged DOM props and handler behavior—for at least the case where `getRootProps` is invoked with props that must override hook `rest`, and a `getLabelProps` merge case if regressions are a concern.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` applies later arguments over earlier ones for normal keys. The previous implementation used `...rest, ...props`, so values from the `getRootProps` argument (`props`) overrode hook-level `rest`. The new call passes `props` before `rest`, so `rest` wins and caller-supplied root props no longer override `useRating`’s remaining props—unlike `getLabelProps` in the same file, which lists `rest` then `props`, and unlike common usage such as `mergeProps(headerProps, props)` in `sidebar.tsx`.
- テスト: The diff only changes runtime merging in `use-rating.tsx` and adds a changeset; it does not add or update tests. The repository requires covering changed behavior for fixes, and the `getRootProps` / `getLabelProps` merge order and `mergeProps` integration are not exercised by new assertions in this PR.

File: packages/react/src/components/rating/use-rating.tsx (hunk 5 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx]: Fixed.

File: packages/react/src/components/rating/use-rating.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx]: Fixed.

File: packages/react/src/components/rating/use-rating.tsx (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx:189]: Fixed.

File: .changeset/rating-merge-props.md (hunk 4 above)
Comment (codex-for-yamada-ui) [reply .changeset/rating-merge-props.md]: Fixed.

File: packages/react/src/components/rating/use-rating.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx]: Fixed.

File: packages/react/src/components/rating/use-rating.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/rating/use-rating.tsx]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
