### PR TITLE
Pagination navigation root props now merge with mergeProps

### LINKED ISSUE #6820: bug(pagination): use mergeProps in getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/pagination/use-pagination.ts:140-148 — `getRootProps` (uses `mergeRefs(ref, rest.ref)`)`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6820

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

usePagination getRootProps uses mergeProps for aria-label, role, rest, props, and ref.

## Is this a breaking change (Yes/No):

No

## Additional Information

Tests: pnpm react test:jsdom --run src/components/pagination/

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/pagination/use-pagination.ts [hunk 1]
```diff
@@ -138,13 +139,18 @@ export const usePagination = ({
...
+    ({ ref, ...props } = {}) =>
+      mergeProps(
+        {
+          "aria-label": t("Pagination"),
+          role: "navigation",
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts]: **Issue:** `rest.ref` is invoked twice per mount after this change. `mergeProps` already merges `rest.ref` into the result at step 2 (because `rest` is passed as an arg and `rest.ref` is kept on it). The final override `{ref: mergeRefs(ref, rest.ref)}` passes `rest.ref` again, and `mergeProps`'s `mergeRef` branch wraps it with the previous ref via `mergeRefs`. Tracing with `rest.ref = R1`, getter `ref = R2`: final callback invokes `R1(node)` (from the wrapped rest.ref), then `R2(node)`, then `R1(node)` again. The previous spread-based code called `R1` exactly once. Consumers passing a ref callback with side effects (e.g. a mount counter, measurement callback) will now observe duplicate invocations — a regression introduced by this fix.

**Fix:** Stop re-passing `rest.ref` in the final override. Either drop `rest.ref` from the final arg (e.g. `{ ref }`) since `rest.ref` is already merged via `rest`, or destructure `rest.ref` out (`const { ref: restRef, ...restProps } = rest`) and use `restRef` only in the final override while passing `restProps` in the middle slot.

File: packages/react/src/components/pagination/use-pagination.ts [hunk 2]
```diff
@@ -138,13 +139,18 @@ export const usePagination = ({
...
+        },
+      )(),
     [rest, t],
   )
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts:156]: **Issue:** The PR changes observable behavior of `getRootProps` (className now cx-merged, style merged, css accumulated, event handlers chained via `handlerAll`, `undefined` no longer overrides, ref composition reworked), but no test covers these new semantics. `use-pagination.test.ts` only tests `range`, and `pagination.test.tsx` has no `getRootProps`/merge assertions. The project rule in CLAUDE.md states "Tests are required: Always write tests when fixing bugs or adding new features", and the precedent PR #6586 (`fix(autocomplete): merge user props with context props via mergeProps`) added 131 lines of tests for equivalent `mergeProps` behavior. Without tests the regression noted in Finding 1 (and future regressions) will not be caught.

**Fix:** Add tests (in `use-pagination.test.ts` or `pagination.test.tsx`) that cover merging of `className`, `style`, `css`, event handlers (e.g. `onClick`), and ref composition (verifying each ref callback is invoked exactly once) when values are supplied via both `usePagination` props (rest) and `getRootProps` props.

File: .changeset/pagination-mergeprops-6820.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
```
Comment (claude-for-yamada-ui) [inline .changeset/pagination-mergeprops-6820.md]: **Issue:** The changeset filename `pagination-mergeprops-6820.md` and the summary `Merge \`getRootProps\` in \`usePagination\` with \`mergeProps\`.` deviate from the established pattern used by all other merge-props changesets in this family (`autocomplete-merge-props.md`, `color-picker-merge-props.md`, `color-selector-merge-props.md`, `date-picker-merge-props.md`, `file-input-merge-props.md`, `native-select-merge-props.md`, `select-merge-props.md`, `chart-props-merge-safely.md`). Those use the `<component>-merge-props.md` filename and a user-facing summary (e.g. "Use `mergeProps` in `Autocomplete` so that user-provided `className`, `style`, `css`, `ref`, and `on*` event handlers are merged with context/getter props instead of being silently overwritten.") that explains the bug impact rather than just restating the refactor.

**Fix:** Rename to `pagination-merge-props.md` and rewrite the summary to describe the user-visible fix (e.g. that consumer-supplied `className`, `style`, `css`, `ref`, and event handlers passed to `usePagination`/`getRootProps` are now correctly merged instead of being overwritten).

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `rest.ref` is invoked twice per mount after this change. `mergeProps` already merges `rest.ref` into the result at step 2 (because `rest` is passed as an arg and `rest.ref` is kept on it). The final override `{ref: mergeRefs(ref, rest.ref)}` passes `rest.ref` again, and `mergeProps`'s `mergeRef` branch wraps it with the previous ref via `mergeRefs`. Tracing with `rest.ref = R1`, getter `ref = R2`: final callback invokes `R1(node)` (from the wrapped rest.ref), then `R2(node)`, then `R1(node)` again. The previous spread-based code called `R1` exactly once. Consumers passing a ref callback with side effects (e.g. a mount counter, measurement callback) will now observe duplicate invocations — a regression introduced by this fix.
- テスト: The PR changes observable behavior of `getRootProps` (className now cx-merged, style merged, css accumulated, event handlers chained via `handlerAll`, `undefined` no longer overrides, ref composition reworked), but no test covers these new semantics. `use-pagination.test.ts` only tests `range`, and `pagination.test.tsx` has no `getRootProps`/merge assertions. The project rule in CLAUDE.md states "Tests are required: Always write tests when fixing bugs or adding new features", and the precedent PR #6586 (`fix(autocomplete): merge user props with context props via mergeProps`) added 131 lines of tests for equivalent `mergeProps` behavior. Without tests the regression noted in Finding 1 (and future regressions) will not be caught.
- 一貫性: The changeset filename `pagination-mergeprops-6820.md` and the summary `Merge \`getRootProps\` in \`usePagination\` with \`mergeProps\`.` deviate from the established pattern used by all other merge-props changesets in this family (`autocomplete-merge-props.md`, `color-picker-merge-props.md`, `color-selector-merge-props.md`, `date-picker-merge-props.md`, `file-input-merge-props.md`, `native-select-merge-props.md`, `select-merge-props.md`, `chart-props-merge-safely.md`). Those use the `<component>-merge-props.md` filename and a user-facing summary (e.g. "Use `mergeProps` in `Autocomplete` so that user-provided `className`, `style`, `css`, `ref`, and `on*` event handlers are merged with context/getter props instead of being silently overwritten.") that explains the bug impact rather than just restating the refactor.

File: packages/react/src/components/pagination/use-pagination.ts [hunk 4]
```diff
@@ -138,13 +139,18 @@ export const usePagination = ({
...
+      mergeProps(
+        {
+          "aria-label": t("Pagination"),
+          role: "navigation",
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
+        },
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts]: **Issue:** `rest` is passed into `mergeProps` and can already contain `rest.ref`, then another `ref` is appended via `{ ref: mergeRefs(ref, rest.ref) }`. Since `mergeProps` auto-merges `ref`, this produces `mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`, so the same callback ref can be invoked twice on mount/unmount.

**Fix:** Split `ref` out of `rest` before calling `mergeProps`, or disable `mergeRef` for this call and assign a single final `ref: mergeRefs(ref, restRef)` once.

File: packages/react/src/components/pagination/use-pagination.ts [hunk 5]
```diff
@@ -138,13 +139,18 @@ export const usePagination = ({
...
+      )(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts:154]: **Issue:** The `getRootProps` path now relies on `mergeProps` semantics (merged events/class/style/ref) instead of direct spread, but existing tests do not assert this merge contract for root props (including single-invocation ref behavior), so this regression surface is currently unguarded.

**Fix:** Add regression tests for `getRootProps`/`Pagination.Root` covering root prop merge behavior (event/class/style merge expectations) and callback ref invocation count.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `rest` is passed into `mergeProps` and can already contain `rest.ref`, then another `ref` is appended via `{ ref: mergeRefs(ref, rest.ref) }`. Since `mergeProps` auto-merges `ref`, this produces `mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`, so the same callback ref can be invoked twice on mount/unmount.
- テスト: The `getRootProps` path now relies on `mergeProps` semantics (merged events/class/style/ref) instead of direct spread, but existing tests do not assert this merge contract for root props (including single-invocation ref behavior), so this regression surface is currently unguarded.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 5 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts:154]: **Issue:** `mergeProps` combines `ref` with `mergeRefs` when a key already exists in `result` (see `packages/react/src/core/components/props.ts:81-86`). Here `rest` (second arg) is merged before the final object, so if `rest` includes `ref`, the final `ref` becomes `mergeRefs(rest.ref, mergeRefs(getRootPropsRef, rest.ref))` instead of a single `mergeRefs(getRootPropsRef, rest.ref)` as in the previous object spread, where the explicit `ref` property **replaced** the value coming from `...rest`. The resulting callback order and duplicate `assignRef` to `rest.ref` differ from the pre-change behavior and from the intended “getter ref + `rest.ref`” pairing.

**Fix:** Decompose `rest` and omit `ref` from the object passed to `mergeProps` (e.g. `const { ref: refFromRest, ...rootRest } = rest` in the hook body and use `rootRest` as the second argument, keeping `{ ref: mergeRefs(ref, refFromRest) }` last), or pass a `rest` copy without `ref` so the last block is the only place that sets `ref`.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 2 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/pagination/use-pagination.ts:156]: **Issue:** The diff only changes `getRootProps`; `packages/react/src/components/pagination/use-pagination.test.ts` still only asserts `range` and does not cover `getRootProps` output, `mergeProps` behavior (e.g. `className` / `onClick` merging), or the `ref` contract for the root.

**Fix:** Add tests that call `getRootProps` with and without a `ref` and with overlapping props from the hook’s `...rest` so the new merge behavior and ref wiring are locked in and cannot regress.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness: `mergeProps` combines `ref` with `mergeRefs` when a key already exists in `result` (see `packages/react/src/core/components/props.ts:81-86`). Here `rest` (second arg) is merged before the final object, so if `rest` includes `ref`, the final `ref` becomes `mergeRefs(rest.ref, mergeRefs(getRootPropsRef, rest.ref))` instead of a single `mergeRefs(getRootPropsRef, rest.ref)` as in the previous object spread, where the explicit `ref` property **replaced** the value coming from `...rest`. The resulting callback order and duplicate `assignRef` to `rest.ref` differ from the pre-change behavior and from the intended “getter ref + `rest.ref`” pairing.
- Tests: The diff only changes `getRootProps`; `packages/react/src/components/pagination/use-pagination.test.ts` still only asserts `range` and does not cover `getRootProps` output, `mergeProps` behavior (e.g. `className` / `onClick` merging), or the `ref` contract for the root.

File: .changeset/pagination-mergeprops-6820.md (hunk 3 above)
Comment (codex-for-yamada-ui) [reply .changeset/pagination-mergeprops-6820.md]: Fixed.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts:156]: Fixed.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts]: Fixed.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts:156]: Fixed.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 5 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts:154]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts:154]: Fixed.

File: packages/react/src/components/pagination/use-pagination.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/pagination/use-pagination.ts]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
