### PR TITLE
fix(dropzone): use mergeProps in PropGetter callbacks

### LINKED ISSUE #6814: bug(dropzone): use mergeProps in remaining PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/dropzone/use-dropzone.ts:233 — `getRootProps``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/dropzone/use-dropzone.ts (getRootProps — already migrated; wraps a third-party getter)
const getRootProps: PropGetter = useCallback(
  (props) =>
    getOriginalRootProps(
      mergeProps(
        {
          id: labelledbyId,
          ...dataProps,
          ...eventProps,
          "aria-disabled": ariaAttr(!interactive),
          "data-accept": dataAttr(dragAccept),
          "data-idle": dataAttr(dragIdle),
          "data-loading": dataAttr(loading),
          "data-reject": dataAttr(dragReject),
        },
        rest,
        props,
      )(),
    ),
  [/* deps */],
)
```

Note: `getRootProps` in the same file has already been migrated and serves as the in-file reference.

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6814

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Migrate the `PropGetter` callbacks in `dropzone` from raw `...rest` / `...props` spread to `mergeProps(...)`, so that consumer-supplied `ref`, `className`, `style`, and event handlers merge correctly with the hook's own values.

## Current behavior (updates)

The affected `PropGetter` callback(s) in `dropzone` merged the hook's `...rest` with the getter's `...props` via raw spread. This silently overwrote (or failed to merge) consumer-supplied `ref`, `className`, `style`, and event handlers.

## New behavior

Each affected callback now builds its output via `mergeProps(defaults, rest, props[, internalHandlers])()`, which merges:
- `ref` via `mergeRefs`
- `className` via `cx`
- `style` via object merge
- event handlers via `handlerAll`

## Is this a breaking change (Yes/No):

No. Behavior converges to what consumers already expect when customizing the affected element(s).

## Additional Information

Part of a broader cleanup tracked across issues #6805-#6839 that replaces raw spread merges in `PropGetter` callbacks across `packages/react` with `mergeProps`.

### CODE REVIEW

File: packages/react/src/components/dropzone/use-dropzone.ts [hunk 1]
```diff
@@ -238,25 +231,24 @@ export const useDropzone = (props: UseDropzoneProps = {}) => {
...
-        "aria-disabled": ariaAttr(!interactive),
-        "data-accept": dataAttr(dragAccept),
-        "data-idle": dataAttr(dragIdle),
-        "data-loading": dataAttr(loading),
-        "data-reject": dataAttr(dragReject),
-        ...rest,
-        ...props,
-      })
+    (props) =>
+      getOriginalRootProps(
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/dropzone/use-dropzone.ts]: **Issue:** This refactor drops `rootRef` from the final composed ref and introduces a regression. The previous implementation destructured `{ ref: rootRef, ...rootProps }` from `getOriginalRootProps` and returned `ref: mergeRefs(ref, rest.ref, rootRef)`, ensuring react-dropzone's internal `rootRef` stayed attached to the DOM element alongside any consumer-supplied ref. The new code merges `rest.ref` and `props.ref` via `mergeProps`, then passes the merged object (including `ref`) into `getOriginalRootProps`. In `react-dropzone@15.0.0` (`node_modules/.../react-dropzone/src/index.js:941-978`), `getRootProps` destructures everything except `ref`, so the incoming `ref` falls into `...rest` and is spread AFTER `[refKey]: rootRef` in the returned object, overriding `rootRef`. As a result, whenever a consumer passes a ref (either via `useDropzone({ ref })` that flows into `rest`, or via `getRootProps({ ref })`), react-dropzone's `rootRef.current` stays `null`, breaking internal behavior that depends on it: `autoFocus` (`rootRef.current.focus()`), drag `contain` checks, `isEqualNode` guard, etc. The PR description claims `ref` is merged via `mergeRefs`, but the actual outcome is the opposite — `rootRef` is no longer forwarded to the DOM. There are also no tests covering ref composition with `rootRef`, so this regression is not guarded.

**Fix:** Continue destructuring `rootRef` out of `getOriginalRootProps(...)` and merge it into the final ref. For example, extract `rootRef` from the result before returning, and compose it with the merged consumer ref, e.g. `({ ref, ...props } = {}) => { const { ref: rootRef, ...rootProps } = getOriginalRootProps(mergeProps({...defaults}, rest, props)()); return { ...rootProps, ref: mergeRefs(ref, rest.ref, rootRef) } }`. Also add a test that asserts the consumer-provided `ref` and react-dropzone's internal `rootRef` both see the root DOM node (e.g., autoFocus still focuses when a consumer ref is provided).

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: This refactor drops `rootRef` from the final composed ref and introduces a regression. The previous implementation destructured `{ ref: rootRef, ...rootProps }` from `getOriginalRootProps` and returned `ref: mergeRefs(ref, rest.ref, rootRef)`, ensuring react-dropzone's internal `rootRef` stayed attached to the DOM element alongside any consumer-supplied ref. The new code merges `rest.ref` and `props.ref` via `mergeProps`, then passes the merged object (including `ref`) into `getOriginalRootProps`. In `react-dropzone@15.0.0` (`node_modules/.../react-dropzone/src/index.js:941-978`), `getRootProps` destructures everything except `ref`, so the incoming `ref` falls into `...rest` and is spread AFTER `[refKey]: rootRef` in the returned object, overriding `rootRef`. As a result, whenever a consumer passes a ref (either via `useDropzone({ ref })` that flows into `rest`, or via `getRootProps({ ref })`), react-dropzone's `rootRef.current` stays `null`, breaking internal behavior that depends on it: `autoFocus` (`rootRef.current.focus()`), drag `contain` checks, `isEqualNode` guard, etc. The PR description claims `ref` is merged via `mergeRefs`, but the actual outcome is the opposite — `rootRef` is no longer forwarded to the DOM. There are also no tests covering ref composition with `rootRef`, so this regression is not guarded.

File: packages/react/src/components/dropzone/use-dropzone.ts [hunk 2]
```diff
@@ -238,25 +231,24 @@ export const useDropzone = (props: UseDropzoneProps = {}) => {
...
+            ...eventProps,
+            "aria-disabled": ariaAttr(!interactive),
+            "data-accept": dataAttr(dragAccept),
+            "data-idle": dataAttr(dragIdle),
+            "data-loading": dataAttr(loading),
+            "data-reject": dataAttr(dragReject),
+          },
+          rest,
+          props,
+        )(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/dropzone/use-dropzone.ts]: **Issue:** The new implementation passes merged `ref` values directly into `getOriginalRootProps(...)`, but `react-dropzone` builds its root props by assigning its internal root ref and then spreading user props. That means a consumer `ref` still overrides the internal dropzone ref, so the PR does not actually satisfy the stated fix ("consumer-supplied `ref` ... merge correctly with the hook's own values").

**Fix:** Keep `className/style/event` merging via `mergeProps`, but handle `ref` separately: call `getOriginalRootProps` without external `ref`, then merge the returned internal ref with consumer refs (`rest.ref` and call-site `props.ref`) when constructing the final return object.

File: packages/react/src/components/dropzone/use-dropzone.ts [hunk 3]
```diff
@@ -238,25 +231,24 @@ export const useDropzone = (props: UseDropzoneProps = {}) => {
...
+      ),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/dropzone/use-dropzone.ts]: **Issue:** This PR changes core prop-merging behavior for `getRootProps` (`className`, `style`, event handlers, and `ref`) but adds no test coverage for those paths. Existing dropzone tests do not assert these merge semantics, so this fix can regress silently.

**Fix:** Add focused tests in `packages/react/src/components/dropzone/dropzone.test.tsx` that verify all intended merge behaviors: `className` concatenation, `style` deep merge behavior, both handlers firing (internal + consumer), and `ref` preserving dropzone functionality while exposing consumer refs.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: The new implementation passes merged `ref` values directly into `getOriginalRootProps(...)`, but `react-dropzone` builds its root props by assigning its internal root ref and then spreading user props. That means a consumer `ref` still overrides the internal dropzone ref, so the PR does not actually satisfy the stated fix ("consumer-supplied `ref` ... merge correctly with the hook's own values").
- テスト: This PR changes core prop-merging behavior for `getRootProps` (`className`, `style`, event handlers, and `ref`) but adds no test coverage for those paths. Existing dropzone tests do not assert these merge semantics, so this fix can regress silently.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 3 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/dropzone/use-dropzone.ts]: **Issue:** `getRootProps` now forwards `mergeProps(..., rest, props)()` straight into `getOriginalRootProps`. In react-dropzone 15, `getRootProps` builds `{ [refKey]: rootRef, ...rest }` for the user-supplied object; any `ref` on that object lives in `rest` and overwrites the library’s `rootRef` instead of composing with it. The previous version avoided passing the callback’s `ref` into `getOriginalRootProps` and then returned `ref: mergeRefs(ref, rest.ref, rootRef)`, so the internal dropzone ref stayed merged. With a consumer or `rest` `ref`, the new path no longer guarantees that the dropzone `rootRef` is included in the final `ref`, which risks breaking drag/click/keyboard behavior tied to the internal root.

**Fix:** After `getOriginalRootProps`, merge the returned `ref` with the merged user refs (e.g. keep the prior `mergeRefs` pattern, or strip `ref` from the object passed in and only merge refs in the return), so the library ref is never replaced by a lone consumer/rest ref. Add a regression test that passes a `ref` to `getRootProps` and assert the node is still the dropzone root (e.g. drop still fires) if feasible.

File: packages/react/src/components/dropzone/use-dropzone.ts [hunk 4]
```diff
@@ -238,25 +231,24 @@ export const useDropzone = (props: UseDropzoneProps = {}) => {
...
-        ...eventProps,
-        "aria-disabled": ariaAttr(!interactive),
-        "data-accept": dataAttr(dragAccept),
-        "data-idle": dataAttr(dragIdle),
-        "data-loading": dataAttr(loading),
-        "data-reject": dataAttr(dragReject),
-        ...rest,
-        ...props,
-      })
+    (props) =>
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/dropzone/use-dropzone.ts]: **Issue:** The diff adds no new or updated tests under `dropzone/`, so the fixed merge behavior for `getRootProps` (refs, `className`, `style`, handlers) is not exercised; project rules require tests for bug fixes.

**Fix:** Extend `dropzone.test.tsx` (or `useDropzone` tests) to cover merged `ref` and at least one of `className` / an event handler on the root to ensure they compose with the hook and dropzone rather than being overwritten.

File: .changeset/dropzone-merge-props.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Fix `dropzone` `PropGetter` callbacks to use `mergeProps` so consumer-supplied `ref`, `className`, `style`, and event handlers merge correctly with the hook's own values instead of being overwritten.
```
Comment (composer-for-yamada-ui) [inline .changeset/dropzone-merge-props.md]: **Issue:** The changeset says “`PropGetter` callbacks” (plural) and describes behavior for all dropzone prop getters, but the diff only changes `getRootProps`. `getInputProps` in the same file still spreads props into `getOriginalInputProps` without `mergeProps`, so the documentation overshoots the actual scope.

**Fix:** Narrow the changeset to `getRootProps` only, or apply the same `mergeProps` pattern to `getInputProps` and then keep the broader wording.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness: `getRootProps` now forwards `mergeProps(..., rest, props)()` straight into `getOriginalRootProps`. In react-dropzone 15, `getRootProps` builds `{ [refKey]: rootRef, ...rest }` for the user-supplied object; any `ref` on that object lives in `rest` and overwrites the library’s `rootRef` instead of composing with it. The previous version avoided passing the callback’s `ref` into `getOriginalRootProps` and then returned `ref: mergeRefs(ref, rest.ref, rootRef)`, so the internal dropzone ref stayed merged. With a consumer or `rest` `ref`, the new path no longer guarantees that the dropzone `rootRef` is included in the final `ref`, which risks breaking drag/click/keyboard behavior tied to the internal root.
- Tests: The diff adds no new or updated tests under `dropzone/`, so the fixed merge behavior for `getRootProps` (refs, `className`, `style`, handlers) is not exercised; project rules require tests for bug fixes.
- Consistency: The changeset says “`PropGetter` callbacks” (plural) and describes behavior for all dropzone prop getters, but the diff only changes `getRootProps`. `getInputProps` in the same file still spreads props into `getOriginalInputProps` without `mergeProps`, so the documentation overshoots the actual scope.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/dropzone/use-dropzone.ts]: Fixed.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/dropzone/use-dropzone.ts]: Fixed.

File: .changeset/dropzone-merge-props.md (hunk 5 above)
Comment (codex-for-yamada-ui) [reply .changeset/dropzone-merge-props.md]: Fixed.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/dropzone/use-dropzone.ts]: Fixed.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/dropzone/use-dropzone.ts]: Fixed.

File: packages/react/src/components/dropzone/use-dropzone.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/dropzone/use-dropzone.ts]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
