### PR TITLE
Native select field props now merge aria and user handlers with mergeProps

### LINKED ISSUE #6818: bug(native-select): use mergeProps in PropGetter callback
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/native-select/use-native-select.tsx:126 — getter`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6818

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

useNativeSelect getFieldProps uses mergeProps for field, rest, props, and ref.

## Is this a breaking change (Yes/No):

No

## Additional Information

Tests: pnpm react test:jsdom --run src/components/native-select/native-select.test.tsx

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/native-select/use-native-select.tsx [hunk 1]
```diff
@@ -115,21 +116,26 @@ export const useNativeSelect = (props: UseNativeSelectProps = {}) => {
...
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
+          children: props.children ?? computedChildren,
+          onBlur: eventProps.onBlur,
+          onFocus: eventProps.onFocus,
+        },
+      )(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx]: **Issue:** `mergeProps` already merges `ref` by default (`mergeRef: true`). Because `rest` is merged earlier and can already contain `ref`, adding `ref: mergeRefs(ref, rest.ref)` in the final argument double-merges `rest.ref`, which can invoke callback refs twice.

**Fix:** Do not combine manual ref merging with automatic ref merging. Either keep `ref: mergeRefs(ref, rest.ref)` and call `mergeProps(... )({ mergeRef: false })`, or keep default merge options and pass only `ref` in the last object so the ref is merged exactly once.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` already merges `ref` by default (`mergeRef: true`). Because `rest` is merged earlier and can already contain `ref`, adding `ref: mergeRefs(ref, rest.ref)` in the final argument double-merges `rest.ref`, which can invoke callback refs twice.

File: packages/react/src/components/native-select/use-native-select.tsx [hunk 2]
```diff
@@ -115,21 +116,26 @@ export const useNativeSelect = (props: UseNativeSelectProps = {}) => {
...
+          tabIndex: interactive ? undefined : -1,
+          ...ariaProps,
+          ...dataProps,
+          "aria-disabled": ariaAttr(!interactive),
+          "aria-label": placeholder,
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx]: **Issue:** `ref: mergeRefs(ref, rest.ref)` double-applies `rest.ref`. Since `rest` is already passed as the second argument to `mergeProps`, its `ref` key is already merged into the result via the built-in `mergeRef` branch of `mergeProps`. Wrapping `rest.ref` again in the final object causes any hook-level callback ref to be invoked twice per update with the same node. This is particularly problematic for React 19 cleanup refs (the cleanup fires twice). The existing test at `native-select.test.tsx:91-105` uses `createRef` and therefore cannot detect this regression.

**Fix:** Pass only the getter-provided ref in the last argument and let `mergeProps` handle merging with `rest.ref`, i.e. `ref,` instead of `ref: mergeRefs(ref, rest.ref)`. Then `mergeRefs` and the local utility import can be removed.

File: packages/react/src/components/native-select/use-native-select.tsx [hunk 3]
```diff
@@ -115,21 +116,26 @@ export const useNativeSelect = (props: UseNativeSelectProps = {}) => {
...
+          children: props.children ?? computedChildren,
+          onBlur: eventProps.onBlur,
+          onFocus: eventProps.onFocus,
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx]: **Issue:** The invocation order of the field's internal focus handlers versus the getter-supplied handlers is reversed. The previous implementation ran `handlerAll(eventProps.onBlur, props.onBlur)` (internal first, then caller). With `mergeProps`, the caller's `onBlur`/`onFocus` is merged in from args[2] (`props`) before args[3] (`{ onBlur: eventProps.onBlur, ... }`), so the composed callback now invokes the caller's handler first and the internal `fieldContext.onBlur` / component-level `onBlur` afterwards. Any consumer of `useNativeSelect` that supplies `onBlur`/`onFocus` through `getFieldProps` and depends on the prior "internal-first" ordering (e.g. state that is set by the field before user-land reads it) will silently change behavior, contradicting the PR description's "Is this a breaking change: No" claim.

**Fix:** Either preserve the original order by explicitly composing with `handlerAll(eventProps.onBlur, props.onBlur)` in the last arg (matching the pre-PR semantics), or document this as an intentional behavioral change in the changeset so consumers are warned. If the new order is truly the desired normalization, call it out in the changeset body.

File: packages/react/src/components/native-select/use-native-select.tsx [hunk 4]
```diff
@@ -115,21 +116,26 @@ export const useNativeSelect = (props: UseNativeSelectProps = {}) => {
...
+        },
+      )(),
     [
       interactive,
       ariaProps,
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx:143]: **Issue:** The refactor changes how `ref`, event handlers, and other props are composed, yet no new tests are added. The current suite covers `className`/`style`/`onClick` and ref object merging, but not the two paths that actually changed: (a) ref callback invocation count (Finding 1) and (b) `onBlur`/`onFocus` merge behavior. Per the project rules, "Tests are required" for bug fixes.

**Fix:** Add tests that (a) use a callback ref passed via `rest.ref` (e.g. through `InputPropsContext`) and assert it is called exactly once per mount/update, and (b) pass `onBlur`/`onFocus` from the component side and verify both `fieldContext` listeners and user listeners run and in the expected order.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `ref: mergeRefs(ref, rest.ref)` double-applies `rest.ref`. Since `rest` is already passed as the second argument to `mergeProps`, its `ref` key is already merged into the result via the built-in `mergeRef` branch of `mergeProps`. Wrapping `rest.ref` again in the final object causes any hook-level callback ref to be invoked twice per update with the same node. This is particularly problematic for React 19 cleanup refs (the cleanup fires twice). The existing test at `native-select.test.tsx:91-105` uses `createRef` and therefore cannot detect this regression.
- 破壊的変更: The invocation order of the field's internal focus handlers versus the getter-supplied handlers is reversed. The previous implementation ran `handlerAll(eventProps.onBlur, props.onBlur)` (internal first, then caller). With `mergeProps`, the caller's `onBlur`/`onFocus` is merged in from args[2] (`props`) before args[3] (`{ onBlur: eventProps.onBlur, ... }`), so the composed callback now invokes the caller's handler first and the internal `fieldContext.onBlur` / component-level `onBlur` afterwards. Any consumer of `useNativeSelect` that supplies `onBlur`/`onFocus` through `getFieldProps` and depends on the prior "internal-first" ordering (e.g. state that is set by the field before user-land reads it) will silently change behavior, contradicting the PR description's "Is this a breaking change: No" claim.
- テスト: The refactor changes how `ref`, event handlers, and other props are composed, yet no new tests are added. The current suite covers `className`/`style`/`onClick` and ref object merging, but not the two paths that actually changed: (a) ref callback invocation count (Finding 1) and (b) `onBlur`/`onFocus` merge behavior. Per the project rules, "Tests are required" for bug fixes.

File: packages/react/src/components/native-select/use-native-select.tsx [hunk 5]
```diff
@@ -115,21 +116,26 @@ export const useNativeSelect = (props: UseNativeSelectProps = {}) => {
...
+          "aria-label": placeholder,
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
+          children: props.children ?? computedChildren,
+          onBlur: eventProps.onBlur,
+          onFocus: eventProps.onFocus,
+        },
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx:139]: **Issue:** `mergeProps` はイベントを `handlerAll(既存, 新規)` で結合するため、引数の並びが「`rest` → `props`（PropGetter 側）→ 最後の `{ onBlur: eventProps.onBlur, onFocus: eventProps.onFocus }`」だと、実行順は **ユーザ側（`rest` / `props`）が先、`eventProps` が後** になる。旧実装は `handlerAll(eventProps.onBlur, props.onBlur)` で **`eventProps` が先**だった。`use-password-input` や `use-switch` も `handlerAll(eventProps, props)` 順であり、フォーム／フィールドの内部状態更新とユーザハンドラの前提順が変わる後方互換リスクがある。

**Fix:** `eventProps` の `onBlur` / `onFocus` を **`rest` と `props` より前**に渡すように `mergeProps` の引数順を組み替える（例: ベース属性オブジェクトの直後に `{ onBlur: eventProps.onBlur, onFocus: eventProps.onFocus }` を置き、その後に `rest`・`props`、最後に `ref` / `children` のみのオブジェクト）。意図した順序になるまで `props.test.tsx` の `mergeProps` のイベント結合テストと照合する。

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 4 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/native-select/use-native-select.tsx:143]: **Issue:** `getFieldProps` の結合方法・イベントの合成順が変わるが、差分に **その挙動を固定するテスト追加がない**。既存の `native-select.test.tsx` はこの順序や `rest` 経由の `onBlur` / `onFocus` の合成を検証していない。

**Fix:** `NativeSelect` に対し、`onBlur` / `onFocus` をルートと `fieldProps`（または `getFieldProps` 経由で渡る想定の props）の両方に渡した場合の **呼び出し順**、および `eventProps` とユーザハンドラの順序が他フィールド系フックと整合することをアサートするテストを追加する。

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` はイベントを `handlerAll(既存, 新規)` で結合するため、引数の並びが「`rest` → `props`（PropGetter 側）→ 最後の `{ onBlur: eventProps.onBlur, onFocus: eventProps.onFocus }`」だと、実行順は **ユーザ側（`rest` / `props`）が先、`eventProps` が後** になる。旧実装は `handlerAll(eventProps.onBlur, props.onBlur)` で **`eventProps` が先**だった。`use-password-input` や `use-switch` も `handlerAll(eventProps, props)` 順であり、フォーム／フィールドの内部状態更新とユーザハンドラの前提順が変わる後方互換リスクがある。
- テスト: `getFieldProps` の結合方法・イベントの合成順が変わるが、差分に **その挙動を固定するテスト追加がない**。既存の `native-select.test.tsx` はこの順序や `rest` 経由の `onBlur` / `onFocus` の合成を検証していない。

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx]: Fixed.

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 5 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx:139]: Fixed.

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx:143]: Fixed.

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx]: Fixed.

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx:143]: Fixed.

File: packages/react/src/components/native-select/use-native-select.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/native-select/use-native-select.tsx]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
