### PR TITLE
fix(accordion): use mergeProps in PropGetter callbacks

### LINKED ISSUE #6806: bug(accordion): use mergeProps in getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/accordion/use-accordion.ts:116-123 — `getRootProps` in `useAccordion``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/accordion/use-accordion.ts (getItemProps — already migrated)
const getItemProps: PropGetter = useCallback(
  (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
  [open, rest],
)
```

Note: `getItemProps` in the same file has already been migrated and serves as the in-file reference.

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6806

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Migrate the `PropGetter` callbacks in `accordion` from raw `...rest` / `...props` spread to `mergeProps(...)`, so that consumer-supplied `ref`, `className`, `style`, and event handlers merge correctly with the hook's own values.

## Current behavior (updates)

The affected `PropGetter` callback(s) in `accordion` merged the hook's `...rest` with the getter's `...props` via raw spread. This silently overwrote (or failed to merge) consumer-supplied `ref`, `className`, `style`, and event handlers.

## New behavior

Each affected callback now builds its output via `mergeProps(defaults, rest, props[, internalHandlers])()`, which merges:
- `ref` via `mergeRefs`
- `className` via `cx`
- `style` via object merge
- event handlers via `handlerAll`

## Is this a breaking change (Yes/No):

No. Behavior converges to what consumers already expect when customizing the affected element(s).

## Additional Information

Part of a broader cleanup tracked across issues #6805-#6839 that replaces raw spread merges in `PropGetter` callbacks across `packages/react` with `mergeProps`.

### CODE REVIEW

File: packages/react/src/components/accordion/use-accordion.ts [hunk 1]
```diff
@@ -235,12 +235,7 @@ export const useAccordionItem = ({
   )
 
   const getItemProps: PropGetter = useCallback(
-    ({ ref, ...props } = {}) => ({
-      "data-expanded": dataAttr(open),
-      ...props,
-      ...rest,
-      ref: mergeRefs(ref, rest.ref),
-    }),
+    (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts]: **Issue:** The PR body states it "Closes #6806", but issue #6806 explicitly targets `getRootProps` in `useAccordion` at `use-accordion.ts:116-123` ("Affected location(s): ... getRootProps in useAccordion"). This PR instead modifies `getItemProps` at lines 237-241 and leaves `getRootProps` (lines 116-123) unchanged, still using raw `...props / ...rest` spread. The issue even notes "`getItemProps` in the same file has already been migrated and serves as the in-file reference" — which was a mistaken premise in the issue (getItemProps was not migrated), but the stated *fix target* remains getRootProps. As shipped, the PR does not resolve #6806.

**Fix:** Migrate `getRootProps` (use-accordion.ts:116-123) to `mergeProps(rest, props)()` as the issue directs. Either additionally keep the `getItemProps` change (and update the PR/issue wording and changeset to cover both), or split it into a separate PR per the "1 PR, 1 fix" rule.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts]: **Issue:** `getItemProps` is deliberately stripped from the exposed `AccordionItemContext` (see `Omit<UseAccordionItemReturn, "getItemProps">` at line 42-45) and the only call site is `accordion.tsx:181` (`<styled.div {...getItemProps()}>`) — invoked with no arguments. In that no-args call, the old code (`{ ...props /*empty*/, ...rest, ref: mergeRefs(undefined, rest.ref) }`) and the new `mergeProps({...}, rest, undefined)()` produce equivalent output (mergeProps skips `undefined` args, and `mergeRefs(undefined, rest.ref) === rest.ref`). The change only affects hypothetical direct `useAccordionItem` consumers that pass args. Combined with Finding 1, the in-tree component behavior is unchanged while the user-reported overwrite (in `getRootProps`, used by `AccordionRoot`) still exists. Matches the "Utility over-application" anti-pattern.

**Fix:** Redirect the migration to `getRootProps`, where there is an actual in-tree call site (`accordion.tsx:122 <styled.div {...getRootProps()}>`) and `rest` flows from `AccordionRoot` consumer props.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts]: **Issue:** For non-merged keys (e.g. `id`, `role`, `data-*`, `aria-*`, `type`), precedence is silently inverted for direct `useAccordionItem` consumers. Old code: `{ "data-expanded", ...props, ...rest, ref }` — `rest` wins over the getter argument. New code: `mergeProps(defaults, rest, props)()` — the getter argument wins over `rest`. So `getItemProps({ id: "x" })` previously returned `rest.id` (if any), and now returns `"x"`. The changeset only mentions "merge correctly ... instead of being overwritten" (i.e. className/style/events/ref), not the precedence inversion for scalar keys.

**Fix:** Either document the precedence change in the changeset, or adjust the argument order (`mergeProps(defaults, props, rest)()` where applicable) if rest-wins was the intended contract. Align with the convention used across sibling PRs in #6805-#6839 and verify against existing tests.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts]: **Issue:** The "Critical Rule" in CLAUDE.md mandates tests for bug fixes. `accordion.test.tsx` contains no test asserting that a consumer-supplied `className`, `style`, `ref`, or event handler passed through the getter merges with (instead of overwrites) the hook's own values — i.e. the exact regression the PR claims to fix. Without such a test, the fix is unverified and unprotected against future regressions.

**Fix:** Add a test (e.g. in `accordion.test.tsx`) that supplies `className`, `style`, `ref`, and an event handler to `AccordionItem` (or directly exercises `useAccordionItem`) and asserts both the hook's value and the consumer's value are present / composed on the rendered element.

File: .changeset/accordion-merge-props.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Fix `accordion` `PropGetter` callbacks to use `mergeProps` so consumer-supplied `ref`, `className`, `style`, and event handlers merge correctly with the hook's own values instead of being overwritten.
```
Comment (claude-for-yamada-ui) [inline .changeset/accordion-merge-props.md]: **Issue:** The changeset wording is plural ("`accordion` `PropGetter` callbacks ... merge correctly"), and the PR title says "PropGetter callbacks" (plural), but only one getter (`getItemProps`) is touched. Meanwhile `getRootProps` (116-123), `getButtonProps` (242-268), `getPanelProps` (270-278), and `getIconProps` (280-289) in the same file continue to use raw spread. This misrepresents scope to changelog readers and, combined with Finding 1, the most important getter (the one the linked issue points to) is not covered.

**Fix:** Either broaden the PR to cover the getters the changeset/title imply (ideally starting with `getRootProps` per #6806), or narrow the wording to singular and explicitly name `getItemProps`.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: The PR body states it "Closes #6806", but issue #6806 explicitly targets `getRootProps` in `useAccordion` at `use-accordion.ts:116-123` ("Affected location(s): ... getRootProps in useAccordion"). This PR instead modifies `getItemProps` at lines 237-241 and leaves `getRootProps` (lines 116-123) unchanged, still using raw `...props / ...rest` spread. The issue even notes "`getItemProps` in the same file has already been migrated and serves as the in-file reference" — which was a mistaken premise in the issue (getItemProps was not migrated), but the stated *fix target* remains getRootProps. As shipped, the PR does not resolve #6806.
- 必要性: `getItemProps` is deliberately stripped from the exposed `AccordionItemContext` (see `Omit<UseAccordionItemReturn, "getItemProps">` at line 42-45) and the only call site is `accordion.tsx:181` (`<styled.div {...getItemProps()}>`) — invoked with no arguments. In that no-args call, the old code (`{ ...props /*empty*/, ...rest, ref: mergeRefs(undefined, rest.ref) }`) and the new `mergeProps({...}, rest, undefined)()` produce equivalent output (mergeProps skips `undefined` args, and `mergeRefs(undefined, rest.ref) === rest.ref`). The change only affects hypothetical direct `useAccordionItem` consumers that pass args. Combined with Finding 1, the in-tree component behavior is unchanged while the user-reported overwrite (in `getRootProps`, used by `AccordionRoot`) still exists. Matches the "Utility over-application" anti-pattern.
- 破壊的変更: For non-merged keys (e.g. `id`, `role`, `data-*`, `aria-*`, `type`), precedence is silently inverted for direct `useAccordionItem` consumers. Old code: `{ "data-expanded", ...props, ...rest, ref }` — `rest` wins over the getter argument. New code: `mergeProps(defaults, rest, props)()` — the getter argument wins over `rest`. So `getItemProps({ id: "x" })` previously returned `rest.id` (if any), and now returns `"x"`. The changeset only mentions "merge correctly ... instead of being overwritten" (i.e. className/style/events/ref), not the precedence inversion for scalar keys.
- テスト: The "Critical Rule" in CLAUDE.md mandates tests for bug fixes. `accordion.test.tsx` contains no test asserting that a consumer-supplied `className`, `style`, `ref`, or event handler passed through the getter merges with (instead of overwrites) the hook's own values — i.e. the exact regression the PR claims to fix. Without such a test, the fix is unverified and unprotected against future regressions.
- スコープと規約: The changeset wording is plural ("`accordion` `PropGetter` callbacks ... merge correctly"), and the PR title says "PropGetter callbacks" (plural), but only one getter (`getItemProps`) is touched. Meanwhile `getRootProps` (116-123), `getButtonProps` (242-268), `getPanelProps` (270-278), and `getIconProps` (280-289) in the same file continue to use raw spread. This misrepresents scope to changelog readers and, combined with Finding 1, the most important getter (the one the linked issue points to) is not covered.

File: packages/react/src/components/accordion/use-accordion.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts]: **Issue:** This patch changes `getItemProps` merge behavior (`ref`, `className`, `style`, and event handlers) but adds no test coverage for that contract. Existing `accordion.test.tsx` cases cover rendering and interaction, but they do not verify these merge semantics, so this fix is currently regression-prone.

**Fix:** Add targeted tests in `packages/react/src/components/accordion/accordion.test.tsx` to assert merged `ref`, `className`, `style`, and event handlers for `Accordion.Item`/`getItemProps` (including that both handlers are called and merged values are preserved).

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: This patch changes `getItemProps` merge behavior (`ref`, `className`, `style`, and event handlers) but adds no test coverage for that contract. Existing `accordion.test.tsx` cases cover rendering and interaction, but they do not verify these merge semantics, so this fix is currently regression-prone.

File: packages/react/src/components/accordion/use-accordion.ts [hunk 3]
```diff
@@ -235,12 +235,7 @@ export const useAccordionItem = ({
...
     [open, rest],
   )
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/accordion/use-accordion.ts:238]: **Issue:** This change fixes consumer `className` / `style` / event handler / `ref` merging for `getItemProps`, but the diff adds no test that exercises those merged props (for example `className` from both `Accordion.Item` and `getItemProps`, or composed handlers). Existing `accordion.test.tsx` only covers default `getItemProps()` usage via `styled.div` and does not assert the regression this PR addresses.

**Fix:** Add a focused test (jsdom or browser test consistent with this package) that renders an item with hook- or component-level props plus extra props passed through `getItemProps`, and assert merged `className`, a composed click handler, or similar behavior.

File: .changeset/accordion-merge-props.md (hunk 2 above)
Comment (composer-for-yamada-ui) [inline .changeset/accordion-merge-props.md]: **Issue:** The changeset states that accordion `PropGetter` “callbacks” are fixed, but the code diff only updates `getItemProps`. `getButtonProps` and `getPanelProps` in the same file still use manual spreads and were not changed, so the release note overstates the scope of the fix.

**Fix:** Narrow the changeset copy to the accordion item root getter (e.g. clarify that `getItemProps` / the item wrapper now uses `mergeProps`), unless you intentionally expand the PR to align the other PropGetters and the note.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: This change fixes consumer `className` / `style` / event handler / `ref` merging for `getItemProps`, but the diff adds no test that exercises those merged props (for example `className` from both `Accordion.Item` and `getItemProps`, or composed handlers). Existing `accordion.test.tsx` only covers default `getItemProps()` usage via `styled.div` and does not assert the regression this PR addresses.
- Scope and conventions: The changeset states that accordion `PropGetter` “callbacks” are fixed, but the code diff only updates `getItemProps`. `getButtonProps` and `getPanelProps` in the same file still use manual spreads and were not changed, so the release note overstates the scope of the fix.

File: packages/react/src/components/accordion/use-accordion.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts]: Fixed.

File: packages/react/src/components/accordion/use-accordion.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts:238]: Fixed.

File: packages/react/src/components/accordion/use-accordion.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts]: Fixed.

File: .changeset/accordion-merge-props.md (hunk 2 above)
Comment (codex-for-yamada-ui) [reply .changeset/accordion-merge-props.md]: Fixed.

File: packages/react/src/components/accordion/use-accordion.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/accordion/use-accordion.ts]: Fixed.

File: .changeset/accordion-merge-props.md (hunk 2 above)
Comment (codex-for-yamada-ui) [reply .changeset/accordion-merge-props.md]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
