### PR TITLE
fix(infinite-scroll-area): restore feed focusability

### LINKED ISSUE #6785: Regression: `InfiniteScrollArea` fails a11y again
### Which package has an issue?

@yamada-ui/react

### Package Version

2.2.0

### Description

The hosted `InfiniteScrollArea` Storybook example appears to have `scrollable-region-focusable` again. The `Root` story renders a scrollable `role="feed"` region that is not keyboard-focusable.

### Link to Reproduction

https://yamada-ui.github.io/yamada-ui/?path=/story/components-infinitescrollarea--root

### Steps to Reproduce

1. Open `https://yamada-ui.github.io/yamada-ui/?path=/story/components-infinitescrollarea--root`.
2. Inspect the `Root` story.
3. Run an accessibility check against the rendered component.
4. Observe the axe `scrollable-region-focusable` failure on the scrollable `role="feed"` region.

### Browser

Chrome

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

No

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

This appears related to previously closed issues #1245 and #1260.

This issue is open to community contribution.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by taroj1205**
Closes #6785

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Restore keyboard focusability for the `InfiniteScrollArea` feed root and add regression coverage for the accessibility behavior.

## Current behavior (updates)

The scrollable `InfiniteScrollArea` root renders with `role="feed"` but can be unfocusable when the component uses its own scroll container, causing the `scrollable-region-focusable` accessibility failure.

## New behavior

The `InfiniteScrollArea` feed root now defaults to `tabIndex={0}` unless a custom `tabIndex` is provided. Focusability regression tests cover both the default and override cases.

## Is this a breaking change (Yes/No):

No

## Additional Information

- Added a changeset for `@yamada-ui/react`.
- Focused component regression test: `pnpm react test:jsdom --run src/components/infinite-scroll-area/infinite-scroll-area.test.tsx`

### CODE REVIEW

File: packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx [hunk 1]
```diff
@@ -67,6 +67,7 @@ export const InfiniteScrollArea = withProvider<
     rootMargin,
     rootRef: rootRefProp,
     startIndex,
+    tabIndex: tabIndexProp,
```
Comment (hirotomoyamada) [inline packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx]: Please remove line.

File: packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx [hunk 2]
```diff
@@ -95,6 +96,7 @@ export const InfiniteScrollArea = withProvider<
         ref={mergeRefs(rootRef, ref)}
         aria-busy="false"
         role="feed"
+        tabIndex={tabIndexProp ?? 0}
```
Comment (hirotomoyamada) [inline packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx]: Please change `tabIndex={0}`.

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
Please correct the commented sections.

File: packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx (hunk 1 above)
Comment (taroj1205) [reply packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx]: Removed.

File: packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx (hunk 2 above)
Comment (taroj1205) [reply packages/react/src/components/infinite-scroll-area/infinite-scroll-area.tsx]: Updated.

**Review by hirotomoyamada — DISMISSED** [review]

**Review by hirotomoyamada — APPROVED** [review]
