### PR TITLE
fix: internationalize `aria-label` within the `useProgress`

### LINKED ISSUE #4672: Internationalize `aria-label` within the `useProgress `
### 概要

Internationalize `aria-label` within the `useProgress`.

### 問題の主張/正当化

none

### 提案する解決策やAPI

_No response_

### 代替案

_No response_

### この機能の実装に参加し、実装を含むプルリクエストを作成しますか？

None

### 追加情報

_No response_

### PR DESCRIPTION
**Pull request by illionillion**
Closes #4672

### CODE REVIEW

File: packages/react/src/components/progress/use-progress.ts [hunk 1]
```diff
@@ -30,18 +31,21 @@ export const useProgress = <Y extends "div" | "svg" = "div">({
 }: UseProgressProps) => {
   const indeterminate = value === null
   const percent = valueToPercent(value ?? 0, min, max)
+  const { t } = useI18n("loading")
 
   const getRootProps = useCallback(
     (props?: HTMLProps<Y>) => ({
-      "aria-label": indeterminate ? "loading..." : `${percent} percent`,
+      "aria-label": indeterminate
+        ? t("loading...")
```
Comment (108yen) [inline packages/react/src/components/progress/use-progress.ts]: `...` does not seem to be available for use in labels.
This is not work.

Comment (illionillion) [reply packages/react/src/components/progress/use-progress.ts]: thanks.
i fixed it.

**Review by 108yen — DISMISSED** [review]

File: packages/react/src/components/progress/use-progress.ts [hunk 2]
```diff
@@ -30,18 +31,19 @@ export const useProgress = <Y extends "div" | "svg" = "div">({
 }: UseProgressProps) => {
   const indeterminate = value === null
   const percent = valueToPercent(value ?? 0, min, max)
+  const { t } = useI18n("loading")
```
Comment (hirotomoyamada) [inline packages/react/src/components/progress/use-progress.ts]: Change `"loading"` to `"progress"`.

File: packages/react/src/providers/i18n-provider/intl/en-US.ts [hunk 3]
```diff
@@ -9,6 +9,10 @@ export default {
   closeButton: {
     Close: "Close",
   },
+  loading: {
```
Comment (hirotomoyamada) [inline packages/react/src/providers/i18n-provider/intl/en-US.ts]: Change `loading` to `progress`.

File: packages/react/src/providers/i18n-provider/intl/ja-JP.ts [hunk 4]
```diff
@@ -9,6 +9,10 @@ export default {
   closeButton: {
     Close: "閉じる",
   },
+  loading: {
```
Comment (hirotomoyamada) [inline packages/react/src/providers/i18n-provider/intl/ja-JP.ts]: Change `loading` to `progress`.

File: packages/react/src/components/progress/use-progress.ts [hunk 5]
```diff
@@ -30,18 +31,19 @@ export const useProgress = <Y extends "div" | "svg" = "div">({
...
 
   const getRootProps = useCallback(
     (props?: HTMLProps<Y>) => ({
-      "aria-label": indeterminate ? "loading..." : `${percent} percent`,
+      "aria-label": indeterminate ? t("loading") : `${percent} ${t("percent")}`,
```
Comment (hirotomoyamada) [inline packages/react/src/components/progress/use-progress.ts]: This `"`${percent} ${t("percent")}`"` is a strange sentence depending on the grammar of your language. Pass `percent` as a callback argument.

File: packages/react/src/components/progress/use-progress.ts (hunk 2 above)
Comment (illionillion) [reply packages/react/src/components/progress/use-progress.ts]: fixed.

File: packages/react/src/providers/i18n-provider/intl/en-US.ts (hunk 3 above)
Comment (illionillion) [reply packages/react/src/providers/i18n-provider/intl/en-US.ts]: fixed.

File: packages/react/src/providers/i18n-provider/intl/ja-JP.ts (hunk 4 above)
Comment (illionillion) [reply packages/react/src/providers/i18n-provider/intl/ja-JP.ts]: fixed.

File: packages/react/src/components/progress/use-progress.ts (hunk 5 above)
Comment (illionillion) [reply packages/react/src/components/progress/use-progress.ts]: Modified as follows.

```tsx
"aria-label": () => indeterminate ? t("loading") : `${percent} ${t("percent")}`,
```

Comment (taroj1205) [reply packages/react/src/components/progress/use-progress.ts]: @illionillion Shouldn't you pass the percentage number to t() so it will work for locales that may have `"percent"` before the number?

Comment (hirotomoyamada) [reply packages/react/src/components/progress/use-progress.ts]: @illionillion @taroj1205 

Yes, that is correct.

Comment (illionillion) [reply packages/react/src/components/progress/use-progress.ts]: @taroj1205 @hirotomoyamada 
Is this what you are talking about?

```tsx
"aria-label": () => indeterminate ? t("loading") : t("percent", { value: percent }),
```

Comment (hirotomoyamada) [reply packages/react/src/components/progress/use-progress.ts]: @illionillion 

Yes, that is correct.

File: packages/react/src/providers/i18n-provider/intl/en-US.ts [hunk 6]
```diff
@@ -21,6 +21,10 @@ export default {
     "Password strength meter": "Password strength meter",
     "Toggle password visibility": "Toggle password visibility",
   },
+  progress: {
+    loading: "loading...",
```
Comment (taroj1205) [inline packages/react/src/providers/i18n-provider/intl/en-US.ts]: Is this supposed to be lowercase?

Comment (hirotomoyamada) [reply packages/react/src/providers/i18n-provider/intl/en-US.ts]: @taroj1205 

No, it should be capitalized.

Comment (illionillion) [reply packages/react/src/providers/i18n-provider/intl/en-US.ts]: I fixed to uppercase.

File: packages/react/src/providers/i18n-provider/intl/ja-JP.ts [hunk 7]
```diff
@@ -21,6 +21,10 @@ export default {
     "Password strength meter": "パスワードの強度",
     "Toggle password visibility": "パスワードの表示を切り替える",
   },
+  progress: {
+    loading: "ローディング...",
+    percent: "{value}パーセント",
```
Comment (taroj1205) [inline packages/react/src/providers/i18n-provider/intl/ja-JP.ts]: Sorry for repeating reviews but wouldn't `読み込み中` sound more natural than `ローディング`?

Comment (hirotomoyamada) [reply packages/react/src/providers/i18n-provider/intl/ja-JP.ts]: @illionillion 

Please change to `"読み込み中"`.

File: packages/react/src/providers/i18n-provider/intl/ja-JP.ts [hunk 8]
```diff
@@ -21,6 +21,10 @@ export default {
     "Password strength meter": "パスワードの強度",
     "Toggle password visibility": "パスワードの表示を切り替える",
   },
+  progress: {
+    loading: "ローディング...",
```
Comment (illionillion) [inline packages/react/src/providers/i18n-provider/intl/ja-JP.ts]:
```suggestion
    loading: "読み込み中...",
```

File: packages/react/src/providers/i18n-provider/intl/ja-JP.ts (hunk 7 above)
Comment (illionillion) [reply packages/react/src/providers/i18n-provider/intl/ja-JP.ts]: @hirotomoyamada @taroj1205 
I fixed.

**Review by hirotomoyamada — APPROVED** [review]
