### PR TITLE
Fix/sidebar auto scroll

### LINKED ISSUE #6212: auto-scroll sidebar to the active component when navigating via search
### Description

When we search a component and navigate to it using search functionality, the main is loaded correctly but the side bar remains in it previous scroll state.
For a better ux experience, the sidebar should automatically scroll the newly active component into view and it must be highlighted .

### Problem Statement/Justification

for reference react offical document use this feature .

Image

Image

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

### AI used

- [x] I did not use AI to create this issue.
- [ ] (If there is no check above) I checked the generated content before submitting.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by SahilJat**
Closes #6212 

## AI used

- [ x ] I did not use AI to create this PR.
- [ ] (If there is no check above) I checked the generated content before submitting.

## Description

added the auto scroll feature in the sidebar when opening a component .

## Current behavior (updates)

the current opened component was not in focus in the sidebar

## New behavior

current opened component will be in the focus in side bar improving the ux experience

## Is this a breaking change (Yes/No):

no

## Additional Information
- Added a `useRef` to `SidebarItem` in `sidebar.tsx`.
- Added a `useEffect` that checks for an exact pathname match.

### CODE REVIEW

File: www/app/[locale]/docs/sidebar.tsx [hunk 1]
```diff
@@ -99,8 +99,16 @@ function SidebarItem({ href, segment, onClick, ...rest }: SidebarItemProps) {
...
+  const ref = useRef<HTMLAnchorElement>(null)
+
+  useEffect(() => {
+    if (current && ref.current) {
+      ref.current.scrollIntoView({ behavior: "smooth", block: "center" })
+    }
+  }, [current])
   return (
     <NextLinkButton
+      ref={ref}
```
Comment (bmthd) [inline www/app/[locale]/docs/sidebar.tsx]: Please use RefCallback instead.

Comment (SahilJat) [reply www/app/[locale]/docs/sidebar.tsx]: thanks for the comment, do you want me to use useCallback instead?

Comment (bmthd) [reply www/app/[locale]/docs/sidebar.tsx]: `useCallback` should also be used. Manipulating APIs on the DOM with `useEffect` and `useRef` is a typical pattern and can be replaced with `useCallback<RefCallback<HTMLAnchorElement>>`.

https://react.dev/reference/react-dom/components/common#ref-callback

Comment (SahilJat) [reply www/app/[locale]/docs/sidebar.tsx]: hi thanks for the tip , i implemented the RefCallBack function , please let me know if it is good to go. Thanks

**Comment by hirotomoyamada** [comment]
@SahilJat @taroj1205 @bmthd 

Thanks for the PR.

I noticed some issues and performance problems, so I made some improvements. Please check the source code.

**Review by taroj1205 — APPROVED** [review]
Thanks!
