### PR TITLE
Enhance accessibility of autocomplete elements

### LINKED ISSUE #3182: The `role="option"` is not set in the options to create `Autocomplete` and `MultiAutocomplete`.
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.4

### Description

The `role="option"` is not set in the options to create `Autocomplete` and `MultiAutocomplete`.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### LINKED ISSUE #3183: Option groups such as `Autocomplete` and `Select` do not have `aria-labelledby` set
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.4

### Description

Option groups such as `Autocomplete` and `Select` do not have `aria-labelledby` set.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### LINKED ISSUE #3184: Non-existent roles are set in `Autocomplete` and `MultiAutocomplete`
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.4

### Description

The roles `"autocomplete-group-container"` and `"autocomplete-group"`, which do not exist in `Autocomplete` and `MultiAutocomplete`, are set.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### LINKED ISSUE #3185: Unnecessary `aria-label` and `aria-multiselectable` are set in `MultiAutocomplete`
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.4

### Description

Unnecessary `aria-label` and `aria-multiselectable` are set in `MultiAutocomplete`.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #3185 
Closes #3184 
Closes #3183 
Closes #3182 

## Description

Enhance accessibility of autocomplete elements.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

File: packages/components/autocomplete/src/multi-autocomplete.tsx [hunk 1]
```diff
@@ -385,8 +384,6 @@ const MultiAutocompleteField = forwardRef<MultiAutocompleteFieldProps, "input">(
 
           <ui.input
             className="ui-multi-autocomplete__field__input"
-            aria-label="Input value"
-            aria-multiselectable="true"
```
Comment (fffk10) [inline packages/components/autocomplete/src/multi-autocomplete.tsx:389]: #3185 OK

File: packages/components/autocomplete/src/use-autocomplete-option.ts [hunk 2]
```diff
@@ -226,8 +227,10 @@ export const useAutocompleteCreate = () => {
 
       return {
         ref,
+        role: "option",
```
Comment (fffk10) [inline packages/components/autocomplete/src/use-autocomplete-option.ts:230]: #3182

**Review by fffk10 — APPROVED** [review]
