### PR TITLE
fix(saturation-slider): use mergeProps for getRootProps

### LINKED ISSUE #6828: bug(saturation-slider): use mergeProps in getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/saturation-slider/use-saturation-slider.ts:184 — getter`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/accordion/use-accordion.ts (getItemProps — already migrated)
const getItemProps: PropGetter = useCallback(
  (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
  [open, rest],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6828

## Description

Uses `mergeProps` in `getRootProps` and keeps explicit CSS variables and gradient styles after merge.

## Is this a breaking change (Yes/No):

No

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts [hunk 1]
```diff
@@ -179,22 +180,24 @@ export const useSaturationSlider = (props: UseSaturationSliderProps = {}) => {
...
-        backgroundImage:
-          "linear-gradient(0deg, #000, transparent), linear-gradient(90deg, #fff, transparent)",
-      },
-      onBlur: handlerAll(props.onBlur, eventProps.onBlur),
-      onFocus: handlerAll(props.onFocus, eventProps.onFocus),
-    }),
+    (props = {}) => {
+      const merged = mergeProps(dataProps, rest, props)()
+
+      return {
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/saturation-slider/use-saturation-slider.ts:186]: **Issue:** CLAUDE.md mandates "Tests are required: Always write tests when fixing bugs or adding new features." This PR fixes prop merging for consumer-supplied `className`, `ref`, and event handlers on `getRootProps`, yet no test exercises the new merging behavior. The existing test `sets className correctly` only checks the default internal class; it does not verify that a consumer-supplied `className`, `onClick`, or `ref` passed alongside the hook's own values is now concatenated/chained/merged rather than overwritten. Without such a test, the fix can silently regress.

**Fix:** Add a test (or tests) to `packages/react/src/components/saturation-slider/saturation-slider.test.tsx` that supply both hook-level and getter-level values for `className` (expect `cx`-merged output), an event handler such as `onClick` (expect both handlers to fire), and a `ref` (expect both refs to receive the node), and assert they are correctly merged by `getRootProps`.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts [hunk 2]
```diff
@@ -179,22 +180,24 @@ export const useSaturationSlider = (props: UseSaturationSliderProps = {}) => {
...
+          ...props.style,
+          "--x": `${Math.abs(s * 100)}%`,
+          "--y": `${Math.abs(100 - v * 100)}%`,
+          backgroundColor: `hsl(${h}, 100%, 50%)`,
+          backgroundImage:
+            "linear-gradient(0deg, #000, transparent), linear-gradient(90deg, #fff, transparent)",
+        },
+        onBlur: handlerAll(props.onBlur, eventProps.onBlur),
+        onFocus: handlerAll(props.onFocus, eventProps.onFocus),
+      }
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/saturation-slider/use-saturation-slider.ts:199]: **Issue:** `mergeProps(dataProps, rest, props)()` already deep-merges `style` (and handles `className`, events, `ref`, `css`) via its default options. The returned object then discards `merged.style` and replaces it with a fresh shallow spread `{ ...rest.style, ...props.style, "--x": ..., "--y": ..., backgroundColor, backgroundImage }`. The shallow re-merge duplicates work, drops `mergeProps`' deep-merge semantics, and diverges from the newly-introduced "use `mergeProps` for correct merging" intent — for any nested style value (e.g. a pseudo `:hover` object spread in CSS-in-JS usage, or a future `dataProps.style`), the shallow spread silently overrides rather than merging, which is exactly what the changeset claims to fix.

**Fix:** Build on top of `merged.style` instead of re-spreading the raw sources, e.g. `style: { ...merged.style, "--x": ..., "--y": ..., backgroundColor: ..., backgroundImage: ... }`. This keeps the fix self-consistent and avoids the redundant re-spread.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: CLAUDE.md mandates "Tests are required: Always write tests when fixing bugs or adding new features." This PR fixes prop merging for consumer-supplied `className`, `ref`, and event handlers on `getRootProps`, yet no test exercises the new merging behavior. The existing test `sets className correctly` only checks the default internal class; it does not verify that a consumer-supplied `className`, `onClick`, or `ref` passed alongside the hook's own values is now concatenated/chained/merged rather than overwritten. Without such a test, the fix can silently regress.
- Necessity / Consistency: `mergeProps(dataProps, rest, props)()` already deep-merges `style` (and handles `className`, events, `ref`, `css`) via its default options. The returned object then discards `merged.style` and replaces it with a fresh shallow spread `{ ...rest.style, ...props.style, "--x": ..., "--y": ..., backgroundColor, backgroundImage }`. The shallow re-merge duplicates work, drops `mergeProps`' deep-merge semantics, and diverges from the newly-introduced "use `mergeProps` for correct merging" intent — for any nested style value (e.g. a pseudo `:hover` object spread in CSS-in-JS usage, or a future `dataProps.style`), the shallow spread silently overrides rather than merging, which is exactly what the changeset claims to fix.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts [hunk 3]
```diff
@@ -179,22 +180,24 @@ export const useSaturationSlider = (props: UseSaturationSliderProps = {}) => {
...
-        "--y": `${Math.abs(100 - v * 100)}%`,
-        backgroundColor: `hsl(${h}, 100%, 50%)`,
-        backgroundImage:
-          "linear-gradient(0deg, #000, transparent), linear-gradient(90deg, #fff, transparent)",
-      },
-      onBlur: handlerAll(props.onBlur, eventProps.onBlur),
-      onFocus: handlerAll(props.onFocus, eventProps.onFocus),
-    }),
+    (props = {}) => {
+      const merged = mergeProps(dataProps, rest, props)()
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/saturation-slider/use-saturation-slider.ts:184]: **Issue:** This change alters the `getRootProps` merge behavior by introducing `mergeProps` (className/event/ref merge semantics), but the PR does not add a regression test for this new code path. Existing `saturation-slider` tests cover component behavior, yet they do not verify the `getRootProps(props)` prop-getter merge contract that this diff specifically changes.

**Fix:** Add a focused test that exercises the changed path directly (for example via `useSaturationSlider` or a component case that passes conflicting root/getter props) and asserts merged `className`, merged event handlers, and merged styles after `getRootProps(...)`.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: This change alters the `getRootProps` merge behavior by introducing `mergeProps` (className/event/ref merge semantics), but the PR does not add a regression test for this new code path. Existing `saturation-slider` tests cover component behavior, yet they do not verify the `getRootProps(props)` prop-getter merge contract that this diff specifically changes.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 3 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/saturation-slider/use-saturation-slider.ts:184]: **Issue:** `getRootProps` で `mergeProps` を使う挙動変更に対し、この差分には `saturation-slider.test.tsx` などのテスト追加・更新が含まれていない。プロジェクト規約ではバグ修正にテストが求められており、`className` の `cx` マージや `ref` の結合など `mergeProps` が担保する経路は既存テスト（例: Root にユーザー `className` を足してもスロット由来のクラスが残るか）では検証されていない。

**Fix:** 少なくとも Root にユーザー定義の `className`（および必要なら `ref`）を渡したとき、期待どおり内部クラスとマージされることをアサートするテストを追加する。再現手順が issue にある場合はそのケースを優先する。

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts [hunk 4]
```diff
@@ -179,22 +180,24 @@ export const useSaturationSlider = (props: UseSaturationSliderProps = {}) => {
...
+          "--y": `${Math.abs(100 - v * 100)}%`,
+          backgroundColor: `hsl(${h}, 100%, 50%)`,
+          backgroundImage:
+            "linear-gradient(0deg, #000, transparent), linear-gradient(90deg, #fff, transparent)",
+        },
+        onBlur: handlerAll(props.onBlur, eventProps.onBlur),
+        onFocus: handlerAll(props.onFocus, eventProps.onFocus),
+      }
+    },
     [dataProps, eventProps, h, rest, s, v],
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/saturation-slider/use-saturation-slider.ts:201]: **Issue:** 同じ `useSaturationSlider` 内の `getInputProps`（この差分の直後、204 行付近）は引き続きオブジェクトスプレッドと `mergeRefs` によるマージに依存している。`getRootProps` だけ `mergeProps` に切り替わったことで、ルートと hidden input で重複キー（`className`、`style`、`css`、イベントハンドラなど）の合成規則がフック内で一致しなくなり、同種の不具合が input 側に残る可能性がある。

**Fix:** `getInputProps` も同様に `mergeProps`（および既存の `visuallyHiddenAttributes` / `ariaProps` / 明示フィールドとの順序）へ揃えるか、意図的にルートのみ対象とする理由をコードコメントや issue 参照で明示し、input 側を別 PR で扱う方針にする。

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: `getRootProps` で `mergeProps` を使う挙動変更に対し、この差分には `saturation-slider.test.tsx` などのテスト追加・更新が含まれていない。プロジェクト規約ではバグ修正にテストが求められており、`className` の `cx` マージや `ref` の結合など `mergeProps` が担保する経路は既存テスト（例: Root にユーザー `className` を足してもスロット由来のクラスが残るか）では検証されていない。
- 一貫性: 同じ `useSaturationSlider` 内の `getInputProps`（この差分の直後、204 行付近）は引き続きオブジェクトスプレッドと `mergeRefs` によるマージに依存している。`getRootProps` だけ `mergeProps` に切り替わったことで、ルートと hidden input で重複キー（`className`、`style`、`css`、イベントハンドラなど）の合成規則がフック内で一致しなくなり、同種の不具合が input 側に残る可能性がある。

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/saturation-slider/use-saturation-slider.ts:199]: Fixed.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/saturation-slider/use-saturation-slider.ts:184]: Fixed.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/saturation-slider/use-saturation-slider.ts:186]: Fixed.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/saturation-slider/use-saturation-slider.ts:201]: Fixed.

File: packages/react/src/components/saturation-slider/use-saturation-slider.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/saturation-slider/use-saturation-slider.ts:184]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
