### PR TITLE
Password input and strength meter props now merge with mergeProps

### LINKED ISSUE #6821: bug(password-input): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/password-input/use-password-input.tsx:68 — getter`
- `packages/react/src/components/password-input/use-strength-meter.ts:35 — getter`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/accordion/use-accordion.ts (getItemProps — already migrated)
const getItemProps: PropGetter = useCallback(
  (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
  [open, rest],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6821

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

usePasswordInput getInputProps and useStrengthMeter getRootProps use mergeProps.

## Is this a breaking change (Yes/No):

No

## Additional Information

Tests: pnpm react test:jsdom --run src/components/password-input/password-input.test.tsx

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/password-input/use-password-input.tsx [hunk 1]
```diff
@@ -60,17 +61,21 @@ export const usePasswordInput = (props: UsePasswordInputProps = {}) => {
...
+          type: visible ? "text" : "password",
+          disabled,
+          ...ariaProps,
+          ...dataProps,
+        },
+        rest,
+        props,
+        eventProps,
+        {
+          ref: mergeRefs(ref, rest.ref),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** `rest.ref` is included twice in the merged result: once via the `rest` argument at line 72 (where `mergeProps` merges it through the `mergeRef` branch), and again via the final object `{ ref: mergeRefs(ref, rest.ref) }`. When `mergeProps` processes that last argument, it runs `mergeRefs(result.ref, mergeRefs(ref, rest.ref))`, so a callback ref passed as `rest.ref` (e.g., a top-level `<PasswordInput ref={...}>` callback) is invoked twice on each node assignment/unassignment. The pre-PR code called each ref exactly once.

**Fix:** Drop `rest.ref` from the manual override. Either inline the inner ref into the base object (`{ ..., ref }`) and let `mergeProps`'s built-in `mergeRef` handling combine it with `rest.ref`, or pass `{ ref: mergeRefs(ref) }` / `{ ref }` as the last argument so only the inner ref is added on top of the already-merged `rest.ref`.

File: packages/react/src/components/password-input/use-password-input.tsx [hunk 2]
```diff
@@ -60,17 +61,21 @@ export const usePasswordInput = (props: UsePasswordInputProps = {}) => {
...
+      mergeProps(
+        {
+          type: visible ? "text" : "password",
+          disabled,
+          ...ariaProps,
+          ...dataProps,
+        },
+        rest,
+        props,
+        eventProps,
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** The invocation order of `onBlur`/`onFocus` handlers silently changed. Before this PR, `onBlur: handlerAll(eventProps.onBlur, props.onBlur)` produced the chain `fieldContext.onBlur -> user-level onBlur -> getInputProps-level onBlur` (inner consumer last). After the refactor, `props` precedes `eventProps` in `mergeProps`, so `mergeEvent` yields `handlerAll(props.onBlur, eventProps.onBlur)`, i.e. `getInputProps-level onBlur -> fieldContext.onBlur -> user-level onBlur`. Because `handlerAll` short-circuits on `ev.defaultPrevented`, this flip can now let a `getInputProps` caller cancel field-context handlers that previously always ran. This behavior change is not called out in the changeset, which only mentions a `mergeProps` refactor.

**Fix:** Preserve the prior order (put `eventProps` before `props` in the `mergeProps` arg list, or keep the explicit `handlerAll(eventProps.onBlur, props.onBlur)`/`onFocus` override after `mergeProps` resolves). If the new order is intentional, document it as a behavior change in the changeset and extend the component tests to lock it in.

File: .changeset/password-input-mergeprops-6821.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Merge `getInputProps` in `usePasswordInput` and `getRootProps` in `useStrengthMeter` with `mergeProps`.
```
Comment (claude-for-yamada-ui) [inline .changeset/password-input-mergeprops-6821.md:5]: **Issue:** The change is landed as a `fix(password-input)` but no test coverage is added in `password-input.test.tsx` for the newly-relevant merge semantics (handler chaining for `onChange`/`onKeyDown`, ref composition across outer+inner calls, `className`/`style`/`css` merging via `mergeProps`). Per CLAUDE.md, tests are required for bug fixes, and without them the subtle ordering/ref behavior identified above can regress silently.

**Fix:** Add unit tests in `packages/react/src/components/password-input/password-input.test.tsx` (and/or a dedicated `use-password-input.test.tsx`) that exercise: multiple refs reaching the field element exactly once, outer+inner `onBlur`/`onFocus`/`onChange` chaining with a `preventDefault` case, and `aria-*`/`data-*` overrides via `getInputProps`. Repeat equivalent coverage for `useStrengthMeter.getRootProps`.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness: `rest.ref` is included twice in the merged result: once via the `rest` argument at line 72 (where `mergeProps` merges it through the `mergeRef` branch), and again via the final object `{ ref: mergeRefs(ref, rest.ref) }`. When `mergeProps` processes that last argument, it runs `mergeRefs(result.ref, mergeRefs(ref, rest.ref))`, so a callback ref passed as `rest.ref` (e.g., a top-level `<PasswordInput ref={...}>` callback) is invoked twice on each node assignment/unassignment. The pre-PR code called each ref exactly once.
- Correctness: The invocation order of `onBlur`/`onFocus` handlers silently changed. Before this PR, `onBlur: handlerAll(eventProps.onBlur, props.onBlur)` produced the chain `fieldContext.onBlur -> user-level onBlur -> getInputProps-level onBlur` (inner consumer last). After the refactor, `props` precedes `eventProps` in `mergeProps`, so `mergeEvent` yields `handlerAll(props.onBlur, eventProps.onBlur)`, i.e. `getInputProps-level onBlur -> fieldContext.onBlur -> user-level onBlur`. Because `handlerAll` short-circuits on `ev.defaultPrevented`, this flip can now let a `getInputProps` caller cancel field-context handlers that previously always ran. This behavior change is not called out in the changeset, which only mentions a `mergeProps` refactor.
- Tests: The change is landed as a `fix(password-input)` but no test coverage is added in `password-input.test.tsx` for the newly-relevant merge semantics (handler chaining for `onChange`/`onKeyDown`, ref composition across outer+inner calls, `className`/`style`/`css` merging via `mergeProps`). Per CLAUDE.md, tests are required for bug fixes, and without them the subtle ordering/ref behavior identified above can regress silently.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** `eventProps` is passed after `props` in `mergeProps(...)`. In this codebase, `mergeProps` composes events in argument order via `handlerAll(previous, next)`, and `handlerAll` short-circuits when `defaultPrevented` is set. This reverses the previous `onBlur`/`onFocus` execution order from this hook, so field/context handlers are no longer guaranteed to run before caller-supplied handlers.

**Fix:** Preserve the previous order by merging `eventProps` before `props` (or explicitly compose `onBlur`/`onFocus` as `handlerAll(eventProps.onBlur, props.onBlur)` and `handlerAll(eventProps.onFocus, props.onFocus)`).

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** `rest` is already included in `mergeProps` (line 72), so `rest.ref` is already part of the merge. Adding `ref: mergeRefs(ref, rest.ref)` in a later merge step causes ref composition to include `rest.ref` twice when present (`mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`), which can invoke callback refs twice.

**Fix:** Compose refs only once. For example, pass `{ ref }` separately and avoid re-including `rest.ref` there, or remove `ref` from `rest` before calling `mergeProps`.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness: `eventProps` is passed after `props` in `mergeProps(...)`. In this codebase, `mergeProps` composes events in argument order via `handlerAll(previous, next)`, and `handlerAll` short-circuits when `defaultPrevented` is set. This reverses the previous `onBlur`/`onFocus` execution order from this hook, so field/context handlers are no longer guaranteed to run before caller-supplied handlers.
- Correctness: `rest` is already included in `mergeProps` (line 72), so `rest.ref` is already part of the merge. Adding `ref: mergeRefs(ref, rest.ref)` in a later merge step causes ref composition to include `rest.ref` twice when present (`mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`), which can invoke callback refs twice.

File: packages/react/src/components/password-input/use-password-input.tsx [hunk 4]
```diff
@@ -60,17 +61,21 @@ export const usePasswordInput = (props: UsePasswordInputProps = {}) => {
...
+        {
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** `mergeProps` に渡す順が `rest`, `props`, `eventProps` のため、同一キーのイベントは後続オブジェクトのハンドラと `handlerAll(result[key], props[key])` で合成されます。`onBlur` / `onFocus` については、直前段の `props` が `result` 側に残ったうえで `eventProps` がマージされ、`handlerAll(props, eventProps)` になります。旧実装は `...rest, ...props` のあと `onBlur: handlerAll(eventProps.onBlur, props.onBlur)` であり、フィールド系（`eventProps`）を先に呼んでいました。`packages/react/src/components/native-select/use-native-select.tsx` の `getFieldProps` も同じ順です。`handlerAll` の呼び出し順は `defaultPrevented` や副作用の観点で意味があるため、リグレッションになります。

**Fix:** 少なくとも `onBlur` / `onFocus` について旧順を保つなら、例: `mergeProps({ ... }, rest, eventProps, props, { ref: mergeRefs(ref, rest.ref) })()` のように `eventProps` を `props` より前に置く。または `mergeProps` の結果に対し、従来どおり `onBlur` / `onFocus` だけ `handlerAll(eventProps, props)` で上書きする。

Comment (composer-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** 旧 `getInputProps` は `...rest, ...props` のため、同じ `on*` キーは右側の `props` だけが残り得ました（上書き）。`mergeProps` の既定では一致する `on[A-Z]…` どうしが関数なら `handlerAll` で連結するため、`rest` と `props` の両方に同じイベントがあれば両方が実行され、従来の「後勝ち」と一致しません。

**Fix:** 従来の上書き意味を保つなら、該当のマージ方針（例: オーバーロードや分割）を意図に合わせて設計し直す。連結が意図なら、changeset や破壊的でない根拠を添え、上記とあわせて挙動を固定する回帰テストを足す。

Comment (composer-for-yamada-ui) [inline packages/react/src/components/password-input/use-password-input.tsx]: **Issue:** 差分内に、`mergeProps` による上記のマージ意味の変化（特に `onBlur` / `onFocus` の呼び出し順と、`rest` と `props` の同一イベント）を検証するテストの追加・更新はありません。リファクタで挙動が変わる可能性が高いパスをテストで固定していない状態です。

**Fix:** 少なくとも `getInputProps` について、フィールド用と呼び出し元の `onBlur` / `onFocus` の呼び出し順、および `rest` と上書き `props` がある場合の意図した結果を表すテストを `password-input` 周辺のテストに追加する。

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` に渡す順が `rest`, `props`, `eventProps` のため、同一キーのイベントは後続オブジェクトのハンドラと `handlerAll(result[key], props[key])` で合成されます。`onBlur` / `onFocus` については、直前段の `props` が `result` 側に残ったうえで `eventProps` がマージされ、`handlerAll(props, eventProps)` になります。旧実装は `...rest, ...props` のあと `onBlur: handlerAll(eventProps.onBlur, props.onBlur)` であり、フィールド系（`eventProps`）を先に呼んでいました。`packages/react/src/components/native-select/use-native-select.tsx` の `getFieldProps` も同じ順です。`handlerAll` の呼び出し順は `defaultPrevented` や副作用の観点で意味があるため、リグレッションになります。
- 正確性: 旧 `getInputProps` は `...rest, ...props` のため、同じ `on*` キーは右側の `props` だけが残り得ました（上書き）。`mergeProps` の既定では一致する `on[A-Z]…` どうしが関数なら `handlerAll` で連結するため、`rest` と `props` の両方に同じイベントがあれば両方が実行され、従来の「後勝ち」と一致しません。
- テスト: 差分内に、`mergeProps` による上記のマージ意味の変化（特に `onBlur` / `onFocus` の呼び出し順と、`rest` と `props` の同一イベント）を検証するテストの追加・更新はありません。リファクタで挙動が変わる可能性が高いパスをテストで固定していない状態です。

File: .changeset/password-input-mergeprops-6821.md (hunk 3 above)
Comment (codex-for-yamada-ui) [reply .changeset/password-input-mergeprops-6821.md:5]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

File: packages/react/src/components/password-input/use-password-input.tsx (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/password-input/use-password-input.tsx]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
