### PR TITLE
fix: replaced icon in `Autocomplete`

### LINKED ISSUE #3534: Replace `AutocompleteIcon` with `LucideIcon`
### Description

Replace `AutocompleteIcon` with `LucideIcon`

### Problem Statement/Justification

Replace the icons from `@yamada-ui/icon` with those from `@yamada-ui/lucide`.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by illionillion**
Closes #3534  

## Description

Replaced by `LucideIcon`

image image image

### CODE REVIEW

File: packages/react/src/components/autocomplete/autocomplete-option.tsx [hunk 1]
```diff
@@ -3,6 +3,7 @@ import type { CSSUIObject, FC } from "../../core"
 import type { UseAutocompleteOptionProps } from "./use-autocomplete-option"
 import { ui } from "../../core"
 import { cx } from "../../utils"
+import { CheckIcon } from "../icon/icons"
```
Comment (108yen) [inline packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: Shouldn't we first remove the icons that are deprecated since we will have to change the import path again?

Comment (illionillion) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: If you jump the code, you'll see that this is a Lucide icon, so there's no need to delete it.

Comment (108yen) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: Shouldn't the writing style be consistent?

Comment (illionillion) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: How is it?

```diff
- import { CheckIcon } from "../icon/icons"
+ import { CheckIcon } from "../icon/"
```

Comment (108yen) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: That is good.
However, the depercated icon in `icon/icons.tsx` takes priority, so you must remove it before making this change.

Comment (illionillion) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: I understand.
But if we remove that deprecated icon, we will have to deal with everything that uses it, so I think we should just merge it as it is now and remove the deprecated one after all the replacements are done and then unify the paths.

Comment (108yen) [reply packages/react/src/components/autocomplete/autocomplete-option.tsx:6]: @illionillion 
OK.
Don't forget to change the import path.

**Review by 108yen — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]
