### PR TITLE
Carousel root props now merge user styles and refs with mergeProps

### LINKED ISSUE #6810: bug(carousel): use mergeProps in remaining PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/carousel/use-carousel.ts:417 — `getRootProps``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Note: `getRootProps` in the same file has already been migrated and serves as the in-file reference.

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6810

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

useCarousel getRootProps uses mergeProps for id, ARIA, rest, and user props.

## Is this a breaking change (Yes/No):

No

## Additional Information

Tests: pnpm react test:jsdom --run src/components/carousel/use-carousel-root.test.ts

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/carousel/use-carousel.ts [hunk 1]
```diff
@@ -410,16 +411,21 @@ export const useCarousel = ({
...
+      mergeProps(
+        {
+          id,
+          "aria-roledescription": "carousel",
+          "data-orientation": orientation,
+        },
+        rest,
+        props,
+        {
+          ref: mergeRefs(ref, rest.ref),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/carousel/use-carousel.ts]: **Issue:** Pre-computing `mergeRefs(ref, rest.ref)` as the 4th arg to `mergeProps` causes `rest.ref` to be invoked twice per mount/unmount. Trace: arg2 seeds `result.ref = rest.ref`; arg3 (props without ref) triggers the default merge path and wraps it into `mergeRefs(rest.ref, undefined)`; arg4's pre-merged ref then wraps again, yielding `mergeRefs(<calls rest.ref>, <calls ref then rest.ref>)`. When the callback fires, `rest.ref` receives the node twice. The referenced fix in issue #6810 avoided this by leaving ref handling to `mergeProps` itself (not destructuring `ref` out of `props`, or passing only the bare user `ref` as the last arg). The PR description explicitly claims `ref` now "combines correctly," but this implementation regresses that case.

**Fix:** Let `mergeProps` do ref merging by dropping the pre-computed `mergeRefs` call, e.g. `mergeProps({id, "aria-roledescription": "carousel", "data-orientation": orientation}, rest, { ref, ...props }, { onMouseEnter, onMouseLeave })()`, matching the pattern suggested in the linked issue.

File: packages/react/src/components/carousel/use-carousel-root.test.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+      className: "user",
+    })
+
+    expect(merged.id).toBe("user-id")
+    expect(String(merged.className)).toContain("hook")
+    expect(String(merged.className)).toContain("user")
+    expect(merged["data-testid"]).toBe("carousel-root")
+    expect(merged["aria-roledescription"]).toBe("carousel")
+  })
+})
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/carousel/use-carousel-root.test.ts]: **Issue:** The PR summary and changeset assert that `className`, `style`, `ref`, and event handlers now combine with hook defaults, but the only test case validates `id`, `className`, `data-testid`, and `aria-roledescription`. `ref` merging (critical given Finding 1), `style` merging, `data-orientation` defaulting, and `onMouseEnter`/`onMouseLeave` chaining with hook defaults (the whole reason for the final `mergeProps` arg) are all untested. This leaves the behavior the PR claims to fix uncovered and would not catch the double-ref invocation.

**Fix:** Add assertions that (a) user-provided `ref` and `rest.ref` callbacks each receive the node exactly once, (b) user-provided `style` objects are merged with hook defaults rather than overwritten, (c) `data-orientation` reflects `orientation`, and (d) user `onMouseEnter`/`onMouseLeave` handlers run alongside the hook's hover handlers (e.g., verify hook hover state toggles while user handler also fires).

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: Pre-computing `mergeRefs(ref, rest.ref)` as the 4th arg to `mergeProps` causes `rest.ref` to be invoked twice per mount/unmount. Trace: arg2 seeds `result.ref = rest.ref`; arg3 (props without ref) triggers the default merge path and wraps it into `mergeRefs(rest.ref, undefined)`; arg4's pre-merged ref then wraps again, yielding `mergeRefs(<calls rest.ref>, <calls ref then rest.ref>)`. When the callback fires, `rest.ref` receives the node twice. The referenced fix in issue #6810 avoided this by leaving ref handling to `mergeProps` itself (not destructuring `ref` out of `props`, or passing only the bare user `ref` as the last arg). The PR description explicitly claims `ref` now "combines correctly," but this implementation regresses that case.
- テスト: The PR summary and changeset assert that `className`, `style`, `ref`, and event handlers now combine with hook defaults, but the only test case validates `id`, `className`, `data-testid`, and `aria-roledescription`. `ref` merging (critical given Finding 1), `style` merging, `data-orientation` defaulting, and `onMouseEnter`/`onMouseLeave` chaining with hook defaults (the whole reason for the final `mergeProps` arg) are all untested. This leaves the behavior the PR claims to fix uncovered and would not catch the double-ref invocation.

File: packages/react/src/components/carousel/use-carousel.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/carousel/use-carousel.ts]: **Issue:** `mergeProps` already merges `ref` keys. Since `rest` contributes `ref`, adding `ref: mergeRefs(ref, rest.ref)` as a later argument creates nested merging (`mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`), which calls `rest.ref` twice per assignment.

**Fix:** Prevent automatic `ref` re-merge here: either remove `ref` from the `rest` object passed into `mergeProps`, or call `mergeProps(... )({ mergeRef: false })` and set `ref: mergeRefs(ref, rest.ref)` exactly once.

File: packages/react/src/components/carousel/use-carousel-root.test.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+    const merged = result.current.getRootProps({
+      id: "user-id",
+      className: "user",
+    })
+
+    expect(merged.id).toBe("user-id")
+    expect(String(merged.className)).toContain("hook")
+    expect(String(merged.className)).toContain("user")
+    expect(merged["data-testid"]).toBe("carousel-root")
+    expect(merged["aria-roledescription"]).toBe("carousel")
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/carousel/use-carousel-root.test.ts:142]: **Issue:** The new test does not verify `style`, `ref`, or event-handler composition even though the PR claims those are fixed. This gap allowed the ref regression above to pass.

**Fix:** Expand this test to cover `style` merge behavior, composed `onMouseEnter`/`onMouseLeave`, and ref-callback invocation counts (both refs called once).

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- Correctness: `mergeProps` already merges `ref` keys. Since `rest` contributes `ref`, adding `ref: mergeRefs(ref, rest.ref)` as a later argument creates nested merging (`mergeRefs(rest.ref, mergeRefs(ref, rest.ref))`), which calls `rest.ref` twice per assignment.
- Test: The new test does not verify `style`, `ref`, or event-handler composition even though the PR claims those are fixed. This gap allowed the ref regression above to pass.

File: packages/react/src/components/carousel/use-carousel-root.test.ts [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+    const merged = result.current.getRootProps({
+      id: "user-id",
+      className: "user",
+    })
+
+    expect(merged.id).toBe("user-id")
+    expect(String(merged.className)).toContain("hook")
+    expect(String(merged.className)).toContain("user")
+    expect(merged["data-testid"]).toBe("carousel-root")
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/carousel/use-carousel-root.test.ts:141]: **Issue:** The new test exercises `id`, `className` / `class`, and `data-*` / `aria-roledescription`, but the linked changeset text at `.changeset/carousel-mergeprops-6810.md:5` also promises correct merging for `style`, `ref`, and event handlers. Those `mergeProps` code paths in `getRootProps` are not asserted, so a regression in `style` merging, `ref` composition, or `onMouseEnter` / `onMouseLeave` composition would not be caught by this PR as written, and the release note is not substantiated by tests.

**Fix:** Add focused assertions in this test (or extend coverage elsewhere) for at least one of: merged `style`, merged refs (e.g. `ref` on `useCarousel` plus `ref` in `getRootProps` / callback refs), and chained pointer handlers, **or** narrow the changeset line so it only claims what the tests and intended behavior both verify.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The new test exercises `id`, `className` / `class`, and `data-*` / `aria-roledescription`, but the linked changeset text at `.changeset/carousel-mergeprops-6810.md:5` also promises correct merging for `style`, `ref`, and event handlers. Those `mergeProps` code paths in `getRootProps` are not asserted, so a regression in `style` merging, `ref` composition, or `onMouseEnter` / `onMouseLeave` composition would not be caught by this PR as written, and the release note is not substantiated by tests.

File: packages/react/src/components/carousel/use-carousel.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/carousel/use-carousel.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/carousel/use-carousel.ts]: Fixed.

File: packages/react/src/components/carousel/use-carousel-root.test.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/carousel/use-carousel-root.test.ts:142]: Fixed.

File: packages/react/src/components/carousel/use-carousel-root.test.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/carousel/use-carousel-root.test.ts]: Fixed.

File: packages/react/src/components/carousel/use-carousel-root.test.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/carousel/use-carousel-root.test.ts:141]: Fixed.

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]

**Review by claude-for-yamada-ui — APPROVED** [review]
