### PR TITLE
fix(segmented-control): use mergeProps for getRootProps and getLabelProps

### LINKED ISSUE #6830: bug(segmented-control): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/segmented-control/use-segmented-control.ts:112 — getter`
- `packages/react/src/components/segmented-control/use-segmented-control.ts:184 — getter (note: `...props` is spread before `...rest`, so the spread order is currently inverted as well)`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/accordion/use-accordion.ts (getItemProps — already migrated)
const getItemProps: PropGetter = useCallback(
  (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
  [open, rest],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6830

## Description

Uses `mergeProps` with `rest` before caller `props` so label props merge correctly (fixes inverted spread order on `getLabelProps`).

## Is this a breaking change (Yes/No):

No

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/segmented-control/use-segmented-control.ts [hunk 1]
```diff
@@ -101,17 +102,20 @@ export const useSegmentedControl = <Y extends string = string>({
...
+          "aria-disabled": ariaAttr(disabled),
+          "aria-orientation": orientation,
+          "data-disabled": dataAttr(disabled),
+          "data-orientation": orientation,
+          "data-readonly": dataAttr(readOnly),
+          role: "radiogroup",
+        },
+        rest,
+        props,
+      )(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/segmented-control/use-segmented-control.ts:118]: **Issue:** This hunk changes `getRootProps` from plain object spreading to `mergeProps(...)`, which changes runtime merge behavior (for example event/class/style/ref handling), but there is no new regression test covering this getter contract. The current `segmented-control.test.tsx` suite only validates rendering/selection/readOnly flows and does not validate conflicting root prop merges.

**Fix:** Add a regression test that exercises `useSegmentedControl(...rest)` + `getRootProps(callerProps)` with overlapping keys and asserts the intended precedence and merged-handler behavior.

File: packages/react/src/components/segmented-control/use-segmented-control.ts [hunk 2]
```diff
@@ -173,17 +177,20 @@ export const useSegmentedControlItem = <Y extends string = string>({
...
+          "data-checked": dataAttr(checked),
+          "data-disabled": dataAttr(trulyDisabled),
+          "data-orientation": orientation,
+          "data-readonly": dataAttr(trulyReadOnly),
+          "data-root-disabled": dataAttr(rootDisabled),
+          "data-root-readonly": dataAttr(rootReadOnly),
+        },
+        rest,
+        props,
+      )(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/segmented-control/use-segmented-control.ts:193]: **Issue:** This hunk changes `getLabelProps` precedence semantics (`...props, ...rest` -> `mergeProps(base, rest, props)`) and merge behavior, but no tests were added to verify this contract shift for hook consumers. Existing tests do not cover label-prop conflict cases, so this behavior change is unverified.

**Fix:** Add regression tests for `getLabelProps` that assert caller `props` precedence over `rest` for conflicting keys and that merged keys (like event handlers/class/style) behave as intended.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: This hunk changes `getRootProps` from plain object spreading to `mergeProps(...)`, which changes runtime merge behavior (for example event/class/style/ref handling), but there is no new regression test covering this getter contract. The current `segmented-control.test.tsx` suite only validates rendering/selection/readOnly flows and does not validate conflicting root prop merges.
- テスト: This hunk changes `getLabelProps` precedence semantics (`...props, ...rest` -> `mergeProps(base, rest, props)`) and merge behavior, but no tests were added to verify this contract shift for hook consumers. Existing tests do not cover label-prop conflict cases, so this behavior change is unverified.

File: packages/react/src/components/segmented-control/use-segmented-control.ts [hunk 3]
```diff
@@ -101,17 +102,20 @@ export const useSegmentedControl = <Y extends string = string>({
...
+          "aria-orientation": orientation,
+          "data-disabled": dataAttr(disabled),
+          "data-orientation": orientation,
+          "data-readonly": dataAttr(readOnly),
+          role: "radiogroup",
+        },
+        rest,
+        props,
+      )(),
     [disabled, id, orientation, readOnly, rest],
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/segmented-control/use-segmented-control.ts:119]: **Issue:** The PR changes how `getRootProps` composes props via `mergeProps` (including chained `on*` handlers, `className`/`style`/`css`/`ref` merging per `packages/react/src/core/components/props.ts`), but `segmented-control.test.tsx` is not updated and still only covers basic render, a11y, and `readOnly`/`disabled`—nothing exercises these merged prop paths for the root or the item label.

**Fix:** Add tests in `packages/react/src/components/segmented-control/segmented-control.test.tsx` that assert composed behavior (for example, extra `className` on `SegmentedControl.Root` / `SegmentedControl.Item`, and/or that both an internal and user `onClick` on the label run when applicable), matching how other `mergeProps` fixes are guarded.

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 2 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/segmented-control/use-segmented-control.ts:193]: **Issue:** `getLabelProps` used object spread `...props, ...rest`, so hook `rest` overrode the `props` argument on overlapping keys; it now uses `mergeProps(..., rest, props)()`, so the argument `props` overrides `rest`, and event/`className`/`style`/`css`/`ref` handling follows `mergeProps` instead of last-spread-wins. That is a real contract change for anyone calling `getLabelProps` with a non-empty object (the `PropGetter` API), while the changeset text only describes ordering relative to “caller `props`” and does not call out this hook-level precedence or composition shift.

**Fix:** Expand `.changeset/segmented-control-merge-props.md` (or release notes) to state that `useSegmentedControlItem`’s `getLabelProps` argument now wins over destructured `rest` and gains `mergeProps` composition semantics; if you consider that incompatible for consumers, use a minor bump or an explicit migration note instead of treating it as an invisible patch-only tweak.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The PR changes how `getRootProps` composes props via `mergeProps` (including chained `on*` handlers, `className`/`style`/`css`/`ref` merging per `packages/react/src/core/components/props.ts`), but `segmented-control.test.tsx` is not updated and still only covers basic render, a11y, and `readOnly`/`disabled`—nothing exercises these merged prop paths for the root or the item label.
- Breaking changes: `getLabelProps` used object spread `...props, ...rest`, so hook `rest` overrode the `props` argument on overlapping keys; it now uses `mergeProps(..., rest, props)()`, so the argument `props` overrides `rest`, and event/`className`/`style`/`css`/`ref` handling follows `mergeProps` instead of last-spread-wins. That is a real contract change for anyone calling `getLabelProps` with a non-empty object (the `PropGetter` API), while the changeset text only describes ordering relative to “caller `props`” and does not call out this hook-level precedence or composition shift.

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 2 above)
Comment (claude-for-yamada-ui) [inline packages/react/src/components/segmented-control/use-segmented-control.ts:193]: **Issue:** CLAUDE.md の "Tests are required: Always write tests when fixing bugs or adding new features" に違反している。PR 本文と linked issue #6830 では `getLabelProps` の spread 順が反転して caller 側 `props`（`className` / `style` / `ref` / イベントハンドラ）が hook の `rest` によって上書きされるバグだと明記されているが、この回帰を捕捉するテストが一切追加されていない。`segmented-control.test.tsx` も既存の 6 ケースのままで、`getLabelProps` に対する caller props のマージ挙動（`className` 連結、`style` マージ、`ref` の mergeRefs、`onClick` の handlerAll）を検証していない。したがって、将来この fix が再反転しても CI で検知できない。

**Fix:** `segmented-control.test.tsx` に、`<SegmentedControl.Item>` に `className` / `style` / `onClick` / `ref` を渡した際に hook 側の data-/aria- 属性とマージ（置換ではなく）されることを assert するテストを追加する。最低でも (1) 消費者の `className` が `ui-segmented-control__item` と併存すること、(2) `onClick` が消費者ハンドラと内部ハンドラの両方を呼ぶこと、(3) `ref` が forward されること、の 3 点を `SegmentedControl.Root` 側（`getRootProps`）と `SegmentedControl.Item` 側（`getLabelProps`）それぞれでカバーすること。

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: CLAUDE.md の "Tests are required: Always write tests when fixing bugs or adding new features" に違反している。PR 本文と linked issue #6830 では `getLabelProps` の spread 順が反転して caller 側 `props`（`className` / `style` / `ref` / イベントハンドラ）が hook の `rest` によって上書きされるバグだと明記されているが、この回帰を捕捉するテストが一切追加されていない。`segmented-control.test.tsx` も既存の 6 ケースのままで、`getLabelProps` に対する caller props のマージ挙動（`className` 連結、`style` マージ、`ref` の mergeRefs、`onClick` の handlerAll）を検証していない。したがって、将来この fix が再反転しても CI で検知できない。

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/segmented-control/use-segmented-control.ts:119]: Fixed.

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/segmented-control/use-segmented-control.ts:193]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/segmented-control/use-segmented-control.ts:193]: Fixed.

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/segmented-control/use-segmented-control.ts:118]: Fixed.

File: packages/react/src/components/segmented-control/use-segmented-control.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/segmented-control/use-segmented-control.ts:193]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
