### PR TITLE
fix(qr-code): use mergeProps for getRootProps

### LINKED ISSUE #6823: bug(qr-code): use mergeProps in getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/qr-code/use-qr-code.tsx:125-128 — `getRootProps``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/accordion/use-accordion.ts (getItemProps — already migrated)
const getItemProps: PropGetter = useCallback(
  (props) => mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
  [open, rest],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6823

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Updates `useQrCode` `getRootProps` to use `mergeProps` so `className`, `style`, `ref`, and event handlers from consumers merge with hook `rest` props.

## Current behavior (updates)

Raw object spread merged `rest` and caller props.

## New behavior

`mergeProps(rest, props)()` applies the standard merge rules for refs, events, class names, and styles.

## Is this a breaking change (Yes/No):

No

## Additional Information

None.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/qr-code/use-qr-code.tsx [hunk 1]
```diff
@@ -123,7 +124,7 @@ export const useQrCode = ({
   }, [encoded.data, encoded.size, pixelSize])
 
   const getRootProps: PropGetter = useCallback(
-    (props = {}) => ({ ...rest, ...props }),
+    (props) => mergeProps(rest, props)(),
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/qr-code/use-qr-code.tsx:127]: **Issue:** This changes the public `useQrCode().getRootProps()` merge semantics, but the PR does not add any regression coverage for that path. The existing `packages/react/src/components/qr-code/qr-code.test.tsx` file only exercises the rendered component shape and class names; it never calls `getRootProps(props)` with overlapping `className`, `style`, `ref`, or event handlers, so this bug fix can regress again without detection.

**Fix:** Add a hook-level regression test for `useQrCode` that calls `getRootProps()` with conflicting caller props and asserts the merged result keeps both sides correctly, especially for `className`, `style`, `ref`, and composed event handlers.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/qr-code/use-qr-code.tsx:127]: **Issue:** The PR claims to fix merging of consumer-supplied `ref`, `className`, `style`, and event handlers passed through `getRootProps`, but no test is added to verify any of these merge behaviors. `qr-code.test.tsx` only covers a11y, displayName, class tokens emitted by the slot system, and tag names — none of them exercises the code path this PR changes (e.g. passing `className`/`style`/`ref`/`onClick` through `QrCode.Root` and asserting they merge with the hook's rest props). CLAUDE.md explicitly states "Tests are required: Always write tests when fixing bugs or adding new features.", so the fix ships without a regression guard.

**Fix:** Add tests to `packages/react/src/components/qr-code/qr-code.test.tsx` (or a new `use-qr-code.test.tsx`) that render `QrCode.Root` with a consumer-supplied `className`, `style`, `ref`, and an event handler and assert they are merged with the hook output (className concatenated, style merged, ref populated, handler invoked). This prevents regressing back to the raw-spread behavior.

Comment (composer-for-yamada-ui) [inline packages/react/src/components/qr-code/use-qr-code.tsx:127]: **Issue:** `getRootProps` のマージ方法が `mergeProps` に変わる一方、`qr-code.test.tsx` は現状レンダリングや `displayName`、`className` の存在のみで、この変更されたマージ経路（例: `useQrCode` を直接使い `getRootProps` に追加 props を渡したときの `className` の結合、`onClick` などイベントの合成）を検証していない。AGENTS.md はバグ修正・機能追加でテストを必須としている。

**Fix:** `qr-code.test.tsx` に `renderHook` 等で `useQrCode` を呼び出し、`getRootProps({ className: "user", onClick: userClick })` のように第2引数を渡したケースで、期待どおり `mergeProps` 相当の結果になることをアサートするテストを追加する（既存の `mergeProps` 単体テストに任せず、このフックの契約を固定する）。

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
Tests are required. The PR changes the public `useQrCode().getRootProps()` merge semantics but has no hook-level regression coverage.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
Tests are required for the merge contract that this PR fixes. Adding regression coverage for `getRootProps` caller-props merging would guard against future regressions.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
Tests are required. The PR changes the merge path of `getRootProps` but lacks a test that pins the new merge contract.

File: packages/react/src/components/qr-code/use-qr-code.tsx (hunk 1 above)
Comment (claude-for-yamada-ui) [reply packages/react/src/components/qr-code/use-qr-code.tsx:127]: Since the previous review, no new commits have been pushed (HEAD is still `32bcc73`), so this concern is unresolved. `packages/react/src/components/qr-code/qr-code.test.tsx` still does not exercise the merge behavior this PR introduces — no test passes a consumer `className`, `style`, `ref`, or event handler through `QrCode.Root`/`getRootProps` and asserts they merge with the hook's rest props. Per CLAUDE.md ("Tests are required: Always write tests when fixing bugs or adding new features."), please add a regression test before this PR is merged.

Comment (composer-for-yamada-ui) [reply packages/react/src/components/qr-code/use-qr-code.tsx:127]: The commit range you asked to review (`32bcc731f39952bfeb5f9059f9e9a1d244f3d63c...32bcc731f39952bfeb5f9059f9e9a1d244f3d63c`) is empty, so there is no new diff to validate. On the current HEAD, `packages/react/src/components/qr-code/qr-code.test.tsx` still only covers a11y, `displayName`, static `className` presence, and tag names—there is still no `renderHook` (or equivalent) coverage for `useQrCode` + `getRootProps({ className, onClick, ... })` to assert `mergeProps(rest, props)()` behavior. Please add the contract test described in the previous review so this thread can be resolved.

---

**補足（日本語）:** 指定の前後コミットが同一のため差分はゼロで、前回依頼した `getRootProps` のマージ経路を固定するテストは追加されていません。作者に追加コミットを取り込むか、正しい旧HEADと新HEADで再レビューしてください。

Comment (codex-for-yamada-ui) [reply packages/react/src/components/qr-code/use-qr-code.tsx:127]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/qr-code/use-qr-code.tsx:127]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/qr-code/use-qr-code.tsx:127]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
