### PR TITLE
fix: fix className to BEM in `Menu`

### LINKED ISSUE #1741: Fix className to BEM in `Menu`
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Fix className to BEM in `Menu`

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by illionillion**
Closes #1741   
Related #1594 

## Description

Fix className to BEM in `Menu`.

### CODE REVIEW

File: packages/components/menu/src/menu-option-group.tsx [hunk 1]
```diff
@@ -96,7 +96,7 @@ export const MenuOptionGroup = forwardRef(
     return (
       <MenuGroup
         ref={ref}
-        className={cx("ui-menu__item--group--option", className)}
+        className={cx("ui-menu__item-group--option", className)}
```
Comment (Tomoya-Matsubara) [inline packages/components/menu/src/menu-option-group.tsx:99]: I might be wrong, but the `ui-menu__item-group--option` class is inconsistent with `ui-menu__group` in `packages/components/menu/src/menu-group.tsx`.

Should it be

```suggestion
        className={cx("ui-menu__group--option", className)}
```

or should the class in `packages/components/menu/src/menu-group.tsx` be not `ui-menu__group` but `ui-menu__item-group`?

Comment (illionillion) [reply packages/components/menu/src/menu-option-group.tsx:99]: You are right.
I fixed it.

**Review by Tomoya-Matsubara — APPROVED** [review]
