### PR TITLE
fix(file-input): merge user props with context props via mergeProps

### LINKED ISSUE #6446: `FileInput` overwrites user props via JSX double spread and context mapper
### Which package has an issue?
@yamada-ui/react

### Package Version
2.2.0

### Description
In `FileInput`, user-provided props are merged with context/getter props via plain object spread (or JSX double spread). This overwrites `className`, `style`, `css`, `ref`, and `on*` event handlers set on the context side when the user also passes them, so users cannot extend styling or attach handlers without destroying the component's internal wiring.

### Link to Reproduction
N/A — code audit; reproducible by passing `className` and `onClick` to the affected sub-component and observing that the context-side value is replaced.

### Steps to Reproduce
1. Render the component with `className` and `onClick` (or `style`) set by the user.
2. Inspect the DOM node.
3. Observe that the context-side props are replaced instead of merged.

### Browser
Chrome

### Operating System
- [x] macOS

### Do you know how to fix the issue?
Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?
Yes

### Additional Information
Use `mergeProps(contextProps, userProps)()` from `packages/react/src/core/components/props.ts` instead of plain spread. See `packages/react/src/components/sidebar/sidebar.tsx` for the reference fix pattern.

**Affected locations:**

- [`packages/react/src/components/file-input/file-input.tsx:117`](https://github.com/yamada-ui/yamada-ui/blob/main/packages/react/src/components/file-input/file-input.tsx#L117) — JSX double spread
- [`packages/react/src/components/file-input/file-input.tsx:127`](https://github.com/yamada-ui/yamada-ui/blob/main/packages/react/src/components/file-input/file-input.tsx#L127) — context mapper

Parent tracking: #6430

### AI used
- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6446

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Replaces unsafe double-spread patterns in `FileInput` with `mergeProps(contextProps, userProps)()` from `../../core`, mirroring the pattern established in PR #6578 (`fix(tree)`).

## Current behavior (updates)

`FileInput` used a raw spread (`{...contextProps, ...userProps}`) which silently overwrote user-provided `className`, `style`, `css`, `ref`, and `on*` event handlers from the context with the component's own props, or vice versa.

## New behavior

`mergeProps` is used to properly merge context props with user props so that `className` values are concatenated, `style` objects are merged, and event handlers are chained — none are silently dropped.

Tests were added to `file-input.test.tsx` to verify that `className`, `style`, and `onClick` from both `InputPropsContext` and the user are all applied.

## Is this a breaking change (Yes/No):

No

## Additional Information

Sub-issue of #6430. Canonical pattern from #6578.

### CODE REVIEW

File: packages/react/src/components/file-input/file-input.tsx [hunk 1]
```diff
@@ -114,7 +114,7 @@ export const FileInput = withProvider<"input", FileInputProps>(
           <styled.input {...getInputProps()} />
         </Portal>
 
-        <styled.div {...varProps} {...getFieldProps()}>
+        <styled.div {...mergeProps(varProps, getFieldProps())()}>
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/file-input/file-input.tsx]: This `mergeProps` call is unnecessary — it is the same anti-pattern as PR #6580.

`varProps` comes from `useInputBorder`, which returns only `--error-border-color` and `--focus-border-color` (plain CSS custom-property strings). It has no `ref`, no `className`, no `style`, no event handlers. `getFieldProps()` returns clickable/aria props. The two objects have no overlapping keys that `mergeProps` would handle differently from a plain spread.

The original `{...varProps, ...getFieldProps()}` was already correct here. Please revert this hunk and keep the plain spread.

File: packages/react/src/components/file-input/file-input.tsx [hunk 2]
```diff
@@ -124,7 +124,7 @@ export const FileInput = withProvider<"input", FileInputProps>(
 )((props) => {
   const context = useInputPropsContext()
 
-  return { ...context, ...props }
+  return mergeProps(context, props)()
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/file-input/file-input.tsx:127]: This change is correct and justified. `context` comes from `useInputPropsContext()` and can carry arbitrary user-provided props (`className`, `style`, `ref`, event handlers) that overlap with the component props. `mergeProps` ensures they are combined instead of silently overwritten.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]

File: packages/react/src/components/file-input/file-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/file-input/file-input.tsx]: Unnecessary `mergeProps`. `varProps` (from `useInputBorder`) contains only CSS custom-property strings (`--error-border-color`, `--focus-border-color`). It has no `ref`, `className`, `style`, or event handlers. `getFieldProps()` returns clickable/aria props with no key overlap that `mergeProps` would handle differently. The original `{...varProps, ...getFieldProps()}` spread was correct. Revert this hunk.

File: packages/react/src/components/file-input/file-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/file-input/file-input.tsx:127]: Correct use of `mergeProps`. The context from `useInputPropsContext()` can carry `className`, `style`, `ref`, and event handlers that would be silently overwritten by a plain spread. `mergeProps` properly chains/merges them.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]

File: packages/react/src/components/file-input/file-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/file-input/file-input.tsx]: Fixed. Reverted to plain spread.

File: packages/react/src/components/file-input/file-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/file-input/file-input.tsx:127]: Acknowledged. Kept as-is.

File: packages/react/src/components/file-input/file-input.tsx (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/file-input/file-input.tsx]: Fixed. Reverted to `{...varProps} {...getFieldProps()}`.

File: packages/react/src/components/file-input/file-input.tsx (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/file-input/file-input.tsx:127]: Acknowledged. Kept as-is.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]
