### PR TITLE
fix(sidebar): use mergeProps for getRootProps and getItemProps

### LINKED ISSUE #6831: bug(sidebar): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/sidebar/use-sidebar.ts:214-221 — `useSidebar.getRootProps``
- `packages/react/src/components/sidebar/use-sidebar.ts:294-301 — `useSidebarGroup.getRootProps``
- `packages/react/src/components/sidebar/use-sidebar.ts:465-492 — `useSidebarItem.getItemProps` (uses `handlerAll` for `onClick` / `onKeyDown`)`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6831

## Description

Applies `mergeProps` to `useSidebar` / `useSidebarGroup` root getters and `useSidebarItem` `getItemProps`, with explicit `onClick` chaining unchanged.

## Is this a breaking change (Yes/No):

No

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/sidebar/use-sidebar.ts [hunk 1]
```diff
@@ -212,11 +217,8 @@ export const useSidebar = ({
...
   const getRootProps: PropGetter<"div"> = useCallback(
-    (props = {}) => ({
-      "data-expanded": dataAttr(open),
-      ...rest,
-      ...props,
-    }),
+    (props = {}) =>
+      mergeProps({ "data-expanded": dataAttr(open) }, rest, props)(),
     [open, rest],
   )
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/sidebar/use-sidebar.ts:224]: **Issue:** The fix for issue #6831 changes prop-merging semantics for `useSidebar.getRootProps`, `useSidebarGroup.getRootProps`, and `useSidebarItem.getItemProps` so that consumer-supplied `ref`, `className`, `style`, and event handlers (e.g. `onKeyDown`) are now merged with the hook's own values instead of being overwritten. However no tests were added to cover this behavior. The existing `sidebar.test.tsx` only asserts internal classnames (line 105 onward) and never passes a consumer `className`/`style`/`ref`/event handler through the affected getters, so there is nothing that would catch a regression of the very bug being fixed. Per CLAUDE.md: "Tests are required: Always write tests when fixing bugs or adding new features."

**Fix:** Add unit tests (or component-level tests) that render/invoke the sidebar with a custom `className`, `style`, `ref`, and a handler (e.g. `onKeyDown` and `onClick` where applicable) on the root, group root, and item, and assert that the consumer value is merged with the hook-owned attributes — e.g. classnames are concatenated (`cx` behavior), styles are shallow-merged, the provided ref is called alongside the internal ref, and the provided handler runs together with the internal one.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The fix for issue #6831 changes prop-merging semantics for `useSidebar.getRootProps`, `useSidebarGroup.getRootProps`, and `useSidebarItem.getItemProps` so that consumer-supplied `ref`, `className`, `style`, and event handlers (e.g. `onKeyDown`) are now merged with the hook's own values instead of being overwritten. However no tests were added to cover this behavior. The existing `sidebar.test.tsx` only asserts internal classnames (line 105 onward) and never passes a consumer `className`/`style`/`ref`/event handler through the affected getters, so there is nothing that would catch a regression of the very bug being fixed. Per CLAUDE.md: "Tests are required: Always write tests when fixing bugs or adding new features."

File: packages/react/src/components/sidebar/use-sidebar.ts [hunk 2]
```diff
@@ -463,21 +462,30 @@ export const useSidebarItem = ({
...
+        },
+        rest,
+        props,
+        { ref },
+        { ref: register },
+      )()
+
+      return {
+        ...merged,
+        onClick: handlerAll(
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/sidebar/use-sidebar.ts:483]: **Issue:** `getItemProps` computes `merged` via `mergeProps(...)`, but the returned `onClick` is rebuilt from `props.onClick` only. This drops `rest.onClick` (for example from `Sidebar.Item`/`itemProps`) even though this change is explicitly about correct prop merging.

**Fix:** Build the final click handler from `merged.onClick` (or explicitly include `rest.onClick`), e.g. `onClick: handlerAll(merged.onClick, !group ? () => onSelectedChange(value) : undefined)`.

File: packages/react/src/components/sidebar/use-sidebar.ts [hunk 3]
```diff
@@ -463,21 +462,30 @@ export const useSidebarItem = ({
...
+          props.onClick,
+          !group ? () => onSelectedChange(value) : undefined,
+        ),
+      }
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/sidebar/use-sidebar.ts:487]: **Issue:** The PR changes the merge strategy in `getItemProps` (`mergeProps`, merged refs, merged style/class/event paths), but no regression test was added for this path. Current sidebar tests do not verify that both root-level and call-site click handlers are preserved by this merge.

**Fix:** Add a test in `sidebar.test.tsx` that provides one click handler through item/root props and another through per-call props, then asserts both are invoked alongside the existing selection behavior.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `getItemProps` computes `merged` via `mergeProps(...)`, but the returned `onClick` is rebuilt from `props.onClick` only. This drops `rest.onClick` (for example from `Sidebar.Item`/`itemProps`) even though this change is explicitly about correct prop merging.
- テスト: The PR changes the merge strategy in `getItemProps` (`mergeProps`, merged refs, merged style/class/event paths), but no regression test was added for this path. Current sidebar tests do not verify that both root-level and call-site click handlers are preserved by this merge.

File: packages/react/src/components/sidebar/use-sidebar.ts (hunk 3 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/sidebar/use-sidebar.ts:487]: **Issue:** `useSidebar` の `getRootProps`、`useSidebarGroup` の `getRootProps`、`useSidebarItem` の `getItemProps` が `mergeProps` ベースに変わり、`className` / `style` / `ref` / イベントの合成挙動が従来の単純スプレッドと異なるが、`sidebar.test.tsx` にこの差分に対応するテスト追加がなく、回帰を防ぐカバレッジがない。

**Fix:** 例として、`Sidebar.Group` / `Sidebar.Item`（または該当コンポーネント）に `className` や `style`、`onClick` を `rest` と渡し props の両方から渡したときに期待どおりマージされること、および `ref` が合成されることをアサートするテストを追加する。

File: .changeset/sidebar-merge-props.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Use `mergeProps` in sidebar `getRootProps` and `getItemProps` for correct prop merging.
```
Comment (composer-for-yamada-ui) [inline .changeset/sidebar-merge-props.md]: **Issue:** サマリーは `getRootProps` と `getItemProps` のみに言及しているが、差分では `useSidebarGroup` の `getRootProps` も同様に `mergeProps` へ置き換えられており、changeset の説明が変更範囲と一致していない。

**Fix:** 一文の要約に `useSidebarGroup` の `getRootProps`（または「sidebar の複数の PropGetter」など）を含め、実際に触れた API を漏れなく列挙する。

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: `useSidebar` の `getRootProps`、`useSidebarGroup` の `getRootProps`、`useSidebarItem` の `getItemProps` が `mergeProps` ベースに変わり、`className` / `style` / `ref` / イベントの合成挙動が従来の単純スプレッドと異なるが、`sidebar.test.tsx` にこの差分に対応するテスト追加がなく、回帰を防ぐカバレッジがない。
- スコープと規約: サマリーは `getRootProps` と `getItemProps` のみに言及しているが、差分では `useSidebarGroup` の `getRootProps` も同様に `mergeProps` へ置き換えられており、changeset の説明が変更範囲と一致していない。

File: packages/react/src/components/sidebar/use-sidebar.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/sidebar/use-sidebar.ts:224]: Fixed.

File: .changeset/sidebar-merge-props.md (hunk 4 above)
Comment (codex-for-yamada-ui) [reply .changeset/sidebar-merge-props.md]: Fixed.

File: packages/react/src/components/sidebar/use-sidebar.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/sidebar/use-sidebar.ts:487]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/sidebar/use-sidebar.ts:487]: Fixed.

File: packages/react/src/components/sidebar/use-sidebar.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/sidebar/use-sidebar.ts:483]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/sidebar/use-sidebar.ts:483]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
