### PR TITLE
fix(toggle): use mergeProps in PropGetter callbacks

### LINKED ISSUE #6837: bug(toggle): use mergeProps in PropGetter callbacks
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/toggle/use-toggle.ts:177 — `useToggle` getter`
- `packages/react/src/components/toggle/use-toggle-group.ts:135-144 — `useToggleGroup.getGroupProps``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

`useToggle` の `getButtonProps` と `useToggleGroup` の `getGroupProps` で `mergeProps` を使い、利用者が渡すプロップが正しくマージされるようにしました。

## Current behavior (updates)

`rest` と getter 引数の `props` を素のスプレッドで結合していました。

## New behavior

`mergeProps` により `className`・`style`・`ref`・イベントハンドラがマージされます。

## Is this a breaking change (Yes/No):

No

## Additional Information

Closes #6837

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: packages/react/src/components/toggle/use-toggle.ts [hunk 1]
```diff
@@ -164,20 +165,23 @@ export const useToggle = <Y extends string = string>(
...
+          "aria-pressed": trulyChecked,
+          "data-active": dataAttr(active),
+          "data-checked": dataAttr(trulyChecked),
+          disabled,
+          tabIndex: interactive ? undefined : -1,
+        },
+        rest,
+        props,
+        { onClick },
+      )(),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/toggle/use-toggle.ts]: **Issue:** `PropGetter` third type parameter `D` is `Merge<HTMLProps<"button">, { "aria-label": string }>`, which declares `aria-label` as required `string`. After this PR, the body returns `mergeProps(...)()` whose `MergeAll` helper applies `Optionalize` to every input, so `aria-label` is widened to `string | undefined`. This produces the blocking CI TypeScript error: `src/components/toggle/use-toggle.ts(163,9): error TS2322 ... Types of property '"aria-label"' are incompatible. Type 'string | undefined' is not assignable to type 'string'.`

**Fix:** Either (a) narrow the return, e.g. cast only the merged result back to the declared `D` via a typed wrapper/overload that preserves required keys, (b) lift the `aria-label` literal into the second argument object in a way that retains its non-optional type (e.g. keep the `aria-label` defaulting inline on the returned object rather than through `mergeProps`), or (c) loosen `PropGetter`'s third parameter to `Merge<HTMLProps<"button">, { "aria-label"?: string }>` if undefined is truly acceptable. Adjust so `pnpm react typecheck` passes.

File: packages/react/src/components/toggle/use-toggle.ts [hunk 2]
```diff
@@ -164,20 +165,23 @@ export const useToggle = <Y extends string = string>(
     undefined,
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/toggle/use-toggle.ts:165]: **Issue:** `CLAUDE.md` mandates tests for every bug fix. The PR claims to fix consumer prop merging (e.g. `onClick`, `className`, `style`, `ref` merging through `mergeProps`) but adds no test asserting the new merge behavior in `use-toggle`/`use-toggle-group`. Without a regression test, a future refactor could silently revert to spread-only merging.

**Fix:** Add a test (e.g. in `toggle.test.tsx` / `toggle-group.test.tsx`) that supplies `onClick`, `className`, and/or `style` through `getButtonProps` / `getGroupProps` and asserts that both the internal handler/class and the consumer-provided one are invoked/composed (i.e. `handlerAll`/`cx` behavior surfaced by `mergeProps`). Include a case covering the group-level `onClick`/`className` merge too.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Type safety (CI failure): `PropGetter` third type parameter `D` is `Merge<HTMLProps<"button">, { "aria-label": string }>`, which declares `aria-label` as required `string`. After this PR, the body returns `mergeProps(...)()` whose `MergeAll` helper applies `Optionalize` to every input, so `aria-label` is widened to `string | undefined`. This produces the blocking CI TypeScript error: `src/components/toggle/use-toggle.ts(163,9): error TS2322 ... Types of property '"aria-label"' are incompatible. Type 'string | undefined' is not assignable to type 'string'.`
- Test coverage (project rule): `CLAUDE.md` mandates tests for every bug fix. The PR claims to fix consumer prop merging (e.g. `onClick`, `className`, `style`, `ref` merging through `mergeProps`) but adds no test asserting the new merge behavior in `use-toggle`/`use-toggle-group`. Without a regression test, a future refactor could silently revert to spread-only merging.

File: packages/react/src/components/toggle/use-toggle.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/toggle/use-toggle.ts]: **Issue:** This refactor changes `getButtonProps` from an object literal to `mergeProps(...)()`, and the callback is no longer assignable to `PropGetter<"button", undefined, Merge<HTMLProps<"button">, { "aria-label": string }>>` (matches the reported `TS2322` in CI). The PR currently cannot pass the TypeScript job.

**Fix:** Return a value that is explicitly compatible with the declared `PropGetter` return type (including a guaranteed `"aria-label": string`), e.g. by narrowing the merged result before return or by restructuring the merge so the final object is typed as `Merge<HTMLProps<"button">, { "aria-label": string }>`.

File: .changeset/olive-bats-wave.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@yamada-ui/react": patch
+---
+
+Use `mergeProps` in `useToggle` and `useToggleGroup` PropGetter callbacks so consumer props merge correctly.
```
Comment (codex-for-yamada-ui) [inline .changeset/olive-bats-wave.md:5]: **Issue:** The changeset claims a behavioral fix ("consumer props merge correctly") for `useToggle` and `useToggleGroup`, but this diff adds no regression tests for that path. Current toggle tests do not verify merged-prop behavior such as handler chaining/prop merging on these updated getters.

**Fix:** Add targeted tests in `toggle.test.tsx` and `toggle-group.test.tsx` that assert merged consumer props behavior (at least event-handler chaining and merged props precedence) for the updated getter code paths.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- 型安全性 (Type safety): This refactor changes `getButtonProps` from an object literal to `mergeProps(...)()`, and the callback is no longer assignable to `PropGetter<"button", undefined, Merge<HTMLProps<"button">, { "aria-label": string }>>` (matches the reported `TS2322` in CI). The PR currently cannot pass the TypeScript job.
- テスト (Tests): The changeset claims a behavioral fix ("consumer props merge correctly") for `useToggle` and `useToggleGroup`, but this diff adds no regression tests for that path. Current toggle tests do not verify merged-prop behavior such as handler chaining/prop merging on these updated getters.

File: packages/react/src/components/toggle/use-toggle.ts [hunk 4]
```diff
@@ -164,20 +165,23 @@ export const useToggle = <Y extends string = string>(
...
-      "data-active": dataAttr(active),
-      "data-checked": dataAttr(trulyChecked),
-      disabled,
-      tabIndex: interactive ? undefined : -1,
-      ...rest,
-      ...props,
-      onClick: handlerAll(rest.onClick, props.onClick, onClick),
-    }),
+    (props = {}) =>
+      mergeProps(
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/toggle/use-toggle.ts]: **Issue:** CI の TypeScript で `getButtonProps` の `useCallback` が `PropGetter<"button", undefined, Merge<HTMLProps<"button">, { "aria-label": string }>>` に代入できず TS2322 になる。`mergeProps(...)()` の推論戻り値型が `PropGetter` の期待する戻り型と一致していないため、PR は型チェックを通過しない。

**Fix:** `mergeProps(...)()` を `PropGetter` の戻り型（上記 `Merge<...>`）に合わせて明示キャストする、または戻り値に付いたラムダへ明示的な戻り値型を付与する。根本対応なら `mergeProps` の戻り型推論を絞るジェネリクス案も検討する。

Comment (composer-for-yamada-ui) [inline packages/react/src/components/toggle/use-toggle.ts]: **Issue:** `getButtonProps` を `mergeProps` に切り替える変更はイベント結合・プロップマージの挙動に直結するが、差分にテストの追加・更新がない。ワークスペース規約では修正にテストが必須。近傍の `toggle.test.tsx` / `toggle-group.test.tsx` にも `onClick` 合成を検証するケースは見当たらない（当該変更の回帰防止が差分上ない）。

**Fix:** 例として、ルート／ボタンに渡した `onClick` とライブラリ内部のハンドラがともに呼ばれること、`use-toggle-group.ts` 側の `getGroupProps` と同様にイベントが上書きではなくマージされることを、該当テストファイルに追加する。

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- 型安全性: CI の TypeScript で `getButtonProps` の `useCallback` が `PropGetter<"button", undefined, Merge<HTMLProps<"button">, { "aria-label": string }>>` に代入できず TS2322 になる。`mergeProps(...)()` の推論戻り値型が `PropGetter` の期待する戻り型と一致していないため、PR は型チェックを通過しない。
- テスト: `getButtonProps` を `mergeProps` に切り替える変更はイベント結合・プロップマージの挙動に直結するが、差分にテストの追加・更新がない。ワークスペース規約では修正にテストが必須。近傍の `toggle.test.tsx` / `toggle-group.test.tsx` にも `onClick` 合成を検証するケースは見当たらない（当該変更の回帰防止が差分上ない）。

File: packages/react/src/components/toggle/use-toggle.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/toggle/use-toggle.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/toggle/use-toggle.ts]: Fixed.

File: packages/react/src/components/toggle/use-toggle.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/toggle/use-toggle.ts]: Fixed.

File: packages/react/src/components/toggle/use-toggle.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/toggle/use-toggle.ts:165]: Fixed.

File: .changeset/olive-bats-wave.md (hunk 3 above)
Comment (codex-for-yamada-ui) [reply .changeset/olive-bats-wave.md:5]: Fixed.

File: packages/react/src/components/toggle/use-toggle.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/toggle/use-toggle.ts]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
