### PR TITLE
fix(avatar): use mergeProps in PropGetter callbacks

### LINKED ISSUE #6807: bug(avatar): use mergeProps in useAvatarGroup getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/avatar/use-avatar-group.ts:25-28 — `getRootProps` in `useAvatarGroup``

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/avatar/use-avatar.ts (getRootProps — already migrated)
const getRootProps: PropGetter = useCallback(
  (props) =>
    mergeProps(
      {
        "data-fallback": dataAttr(!!fallbackMessage),
        "data-loaded": dataAttr(loaded),
      },
      rest,
      props,
    )(),
  [loaded, fallbackMessage, rest],
)
```

Note: `useAvatar.getRootProps` in the same component has already been migrated and serves as the in-component reference.

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #6807

## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

Migrate the `PropGetter` callbacks in `avatar` from raw `...rest` / `...props` spread to `mergeProps(...)`, so that consumer-supplied `ref`, `className`, `style`, and event handlers merge correctly with the hook's own values.

## Current behavior (updates)

The affected `PropGetter` callback(s) in `avatar` merged the hook's `...rest` with the getter's `...props` via raw spread. This silently overwrote (or failed to merge) consumer-supplied `ref`, `className`, `style`, and event handlers.

## New behavior

Each affected callback now builds its output via `mergeProps(defaults, rest, props[, internalHandlers])()`, which merges:
- `ref` via `mergeRefs`
- `className` via `cx`
- `style` via object merge
- event handlers via `handlerAll`

## Is this a breaking change (Yes/No):

No. Behavior converges to what consumers already expect when customizing the affected element(s).

## Additional Information

Part of a broader cleanup tracked across issues #6805-#6839 that replaces raw spread merges in `PropGetter` callbacks across `packages/react` with `mergeProps`.

### CODE REVIEW

File: packages/react/src/components/avatar/use-avatar.ts [hunk 1]
```diff
@@ -92,12 +92,15 @@ export const useAvatar = ({
...
 
   const getRootProps: PropGetter = useCallback(
-    (props) => ({
-      ...rest,
-      ...props,
-      "data-fallback": dataAttr(!!fallbackMessage),
-      "data-loaded": dataAttr(loaded),
-    }),
+    (props) =>
+      mergeProps(
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts]: **Issue**: `mergeProps` is called with the computed `data-fallback` / `data-loaded` object first, so any caller-provided `data-loaded` or `data-fallback` in `rest` or `props` now overrides the hook's actual state. This can desynchronize the root's `_loaded` styling from the real image-loading state because `avatar.style.ts` keys off `data-loaded`.

**Fix**: Merge `rest` and `props` first, then apply the computed `data-*` attributes last:
```ts
mergeProps(rest, props, {
  "data-fallback": dataAttr(!!fallbackMessage),
  "data-loaded": dataAttr(loaded),
})()
```

Comment (composer-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts]: **Issue**: `mergeProps` applies later arguments over earlier ones for ordinary keys. With `mergeProps({ "data-fallback": ..., "data-loaded": ... }, rest, props)()`, both `rest` and `props` can overwrite the hook-managed `data-fallback` and `data-loaded` when those keys are present, reversing the previous `{ ...rest, ...props, "data-fallback": ..., "data-loaded": ... }` behavior.

**Fix**: Put internal attributes last: `mergeProps(rest, props, { "data-fallback": ..., "data-loaded": ... })()`.

File: packages/react/src/components/avatar/use-avatar.ts [hunk 2]
```diff
@@ -92,12 +92,15 @@ export const useAvatar = ({
   const getGroupProps: PropGetter = useCallback((props) => ({ ...props }), [])
 
   const getRootProps: PropGetter = useCallback(
```
Comment (codex-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts:94]: **Issue**: This bug fix changes how the avatar root merges props, but the PR adds no regression test covering the new merge semantics.

**Fix**: Add an avatar regression test that exercises the root prop merge path and asserts merged `className`/`style`/handler behavior while the hook's computed `data-loaded` attribute still reflects the actual load state.

Comment (composer-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts:94]: **Issue**: The diff changes how root props are composed (including merge semantics for overlapping keys), but no tests were added or updated to lock in the intended precedence for `getRootProps`.

**Fix**: Add tests (e.g. in `avatar.test.tsx`) that cover merged `className` / `style` / handlers on the root and assert hook-owned `data-*` stay authoritative when overlapping props are passed through `rest` or the getter argument.

**Review by codex-for-yamada-ui — DISMISSED** [review]
Two concerns on the root prop merge refactor: (1) the mergeProps argument order lets caller-provided data-* attrs override the hook's computed state, and (2) the behavioral change has no regression test coverage.

**Review by composer-for-yamada-ui — DISMISSED** [review]
Two concerns overlap with Codex: mergeProps argument order reverses the previous internal-attrs-last semantics, and no tests were added to lock in the intended merge behavior.

File: packages/react/src/components/avatar/use-avatar.ts [hunk 3]
```diff
@@ -92,12 +92,15 @@ export const useAvatar = ({
...
+      mergeProps(
+        {
+          "data-fallback": dataAttr(!!fallbackMessage),
+          "data-loaded": dataAttr(loaded),
+        },
+        rest,
+        props,
+      )(),
     [loaded, fallbackMessage, rest],
   )
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts:101]: **Issue:** The PR claims to fix a bug where consumer-supplied `ref`/`className`/`style`/event handlers were silently overwritten in `getRootProps`, but no test was added to exercise the new merge behavior. CLAUDE.md mandates tests for bug fixes, and all preceding PRs in this cleanup series (for example #6597 color-selector, #6596 color-picker, #6590 date-picker, #6588 native-select) added dedicated merge tests in the corresponding `*.test.tsx`. Without tests, the fix is unverified and can silently regress.

**Fix:** Add tests to `packages/react/src/components/avatar/avatar.test.tsx` covering the four contract points: (a) `className` from `rest` (e.g. via `<Avatar className="foo" />`) is concatenated with consumer `className` (e.g. via `getRootProps({ className: "bar" })` in a custom harness, or via the `Avatar` component itself using class-merging), (b) `style` objects merge, (c) both `onClick` handlers fire, (d) both refs resolve. Follow the structure used by the previously merged `color-selector`/`color-picker` tests.

File: packages/react/src/components/avatar/use-avatar.ts [hunk 4]
```diff
@@ -92,12 +92,15 @@ export const useAvatar = ({
...
-    }),
+    (props) =>
+      mergeProps(
+        {
+          "data-fallback": dataAttr(!!fallbackMessage),
+          "data-loaded": dataAttr(loaded),
+        },
+        rest,
+        props,
+      )(),
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts]: **Issue:** The argument order passed to `mergeProps` reverses the priority of `data-fallback`/`data-loaded` compared with the previous implementation. Originally these data attributes were spread last (`{ ...rest, ...props, "data-fallback": ..., "data-loaded": ... }`), so the hook's values always won. With `mergeProps(dataAttrs, rest, props)()`, because the generic fallback inside `mergeProps` is `result[key] = !isUndefined(props[key]) ? props[key] : result[key]` (see `packages/react/src/core/components/props.ts:123`), a consumer (or a prop accidentally forwarded via `...rest` to `useAvatar`) passing `data-fallback`/`data-loaded` will now silently override the hook's internal state. The PR description explicitly states behavior should "converge to what consumers already expect" — overridable internal state markers are the opposite of that.

**Fix:** Put the hook-owned data attributes last so they retain their previous priority, e.g. `mergeProps(rest, props, { "data-fallback": dataAttr(!!fallbackMessage), "data-loaded": dataAttr(loaded) })()`. Add a regression test that passes conflicting `data-fallback` via props and asserts the hook's value still wins.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The PR claims to fix a bug where consumer-supplied `ref`/`className`/`style`/event handlers were silently overwritten in `getRootProps`, but no test was added to exercise the new merge behavior. CLAUDE.md mandates tests for bug fixes, and all preceding PRs in this cleanup series (for example #6597 color-selector, #6596 color-picker, #6590 date-picker, #6588 native-select) added dedicated merge tests in the corresponding `*.test.tsx`. Without tests, the fix is unverified and can silently regress.
- Correctness: The argument order passed to `mergeProps` reverses the priority of `data-fallback`/`data-loaded` compared with the previous implementation. Originally these data attributes were spread last (`{ ...rest, ...props, "data-fallback": ..., "data-loaded": ... }`), so the hook's values always won. With `mergeProps(dataAttrs, rest, props)()`, because the generic fallback inside `mergeProps` is `result[key] = !isUndefined(props[key]) ? props[key] : result[key]` (see `packages/react/src/core/components/props.ts:123`), a consumer (or a prop accidentally forwarded via `...rest` to `useAvatar`) passing `data-fallback`/`data-loaded` will now silently override the hook's internal state. The PR description explicitly states behavior should "converge to what consumers already expect" — overridable internal state markers are the opposite of that.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts]: **Issue:** This bug fix changes `getRootProps` merge behavior (switching from spread overwrite to `mergeProps` composition), but there is no accompanying test in the PR diff to verify the newly intended behavior (merged handlers/refs/className/style). The current avatar tests only cover rendering/fallback/group behavior, so this regression path remains unguarded.

**Fix:** Add focused tests for the changed path (e.g., exercise `getRootProps` behavior via `useAvatar` or component-level integration) that assert callback composition and prop merging semantics (`ref`, `className`, `style`, and event handlers) so the fix is enforced going forward.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- Testing: This bug fix changes `getRootProps` merge behavior (switching from spread overwrite to `mergeProps` composition), but there is no accompanying test in the PR diff to verify the newly intended behavior (merged handlers/refs/className/style). The current avatar tests only cover rendering/fallback/group behavior, so this regression path remains unguarded.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 4 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts]: **Issue:** `mergeProps` applies arguments left-to-right; for keys already in `result`, a defined value from a later argument overwrites (`props.ts` の `result[key] = !isUndefined(props[key]) ? props[key] : result[key]`). Putting the `data-fallback` / `data-loaded` object first means values from `rest` (and then `props`) can replace the hook’s `dataAttr(!!fallbackMessage)` and `dataAttr(loaded)`. The previous object spread always set those two keys last, so the hook’s state always won. This can desync internal styling/state from the real loaded/fallback state when consumers pass those `data-*` attributes (they are valid `HTMLProps` on the root).

**Fix:** Merge consumer props first, then apply hook data attributes last, e.g. `mergeProps(rest, props, { "data-fallback": dataAttr(!!fallbackMessage), "data-loaded": dataAttr(loaded) })()`, so ref/className/style/events still compose across `rest` and `props` while the hook-owned `data-*` values keep final precedence.

File: packages/react/src/components/avatar/use-avatar.ts [hunk 5]
```diff
@@ -92,12 +92,15 @@ export const useAvatar = ({
...
     [loaded, fallbackMessage, rest],
```
Comment (composer-for-yamada-ui) [inline packages/react/src/components/avatar/use-avatar.ts:100]: **Issue:** The diff changes `getRootProps` behavior (the stated goal is correct merging of `ref`, `className`, `style`, and event handlers), but `avatar.test.tsx` in this package still only covers rendering and group behavior; nothing asserts merged refs/handlers/styles or the intended precedence of hook `data-*` vs spread props. Repository rules expect tests for bug fixes on changed code paths.

**Fix:** Add focused tests (e.g. render `Avatar` with `className`, `style`, `onClick`, and `ref` on the root plus `getRootProps`-style usage if applicable) asserting composition rather than last-writer wins, and a case that hook `data-loaded` / `data-fallback` stay authoritative when overlapping keys appear on the root.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- 正確性: `mergeProps` applies arguments left-to-right; for keys already in `result`, a defined value from a later argument overwrites (`props.ts` の `result[key] = !isUndefined(props[key]) ? props[key] : result[key]`). Putting the `data-fallback` / `data-loaded` object first means values from `rest` (and then `props`) can replace the hook’s `dataAttr(!!fallbackMessage)` and `dataAttr(loaded)`. The previous object spread always set those two keys last, so the hook’s state always won. This can desync internal styling/state from the real loaded/fallback state when consumers pass those `data-*` attributes (they are valid `HTMLProps` on the root).
- テスト: The diff changes `getRootProps` behavior (the stated goal is correct merging of `ref`, `className`, `style`, and event handlers), but `avatar.test.tsx` in this package still only covers rendering and group behavior; nothing asserts merged refs/handlers/styles or the intended precedence of hook `data-*` vs spread props. Repository rules expect tests for bug fixes on changed code paths.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 3 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts:101]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 4 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts:94]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts:94]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts]: Fixed.

File: packages/react/src/components/avatar/use-avatar.ts (hunk 5 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/avatar/use-avatar.ts:100]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]
