### PR TITLE
fix(slider): use mergeProps in getRootProps

### LINKED ISSUE #6832: bug(slider): use mergeProps in getRootProps
### Which package has an issue?

@yamada-ui/react

### Package Version

main (current)

### Description

The `PropGetter` callback(s) listed below merge the hook's `...rest` and the getter's `...props` via raw spread, instead of using `mergeProps`. As a result, consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten by (or fail to merge with) the hook's own values.

**Affected location(s):**

- `packages/react/src/components/slider/use-slider.ts:297-321 — `getRootProps` (mixes `...dataProps`, `...rest`, `...props` with `handlerAll` for `onBlur` / `onFocus`)`

### Link to Reproduction

N/A — code-level bug visible by inspection. Any consumer that supplies `className`, `style`, `ref`, or an event handler through the affected getter exhibits the bug.

### Steps to Reproduce

1. Render the affected component / hook consumer.
2. Pass a custom `className` (or `style`, `ref`, event handler) through the affected getter.
3. Observe that the consumer-supplied value is overwritten or fails to merge with the hook's own value, instead of being properly combined.

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

**Suggested fix**

Replace the spread merge with `mergeProps`. Reference (an analogous callback that has already been migrated in the codebase):

```ts
// packages/react/src/components/carousel/use-carousel.ts (getRootProps — already migrated)
const getRootProps: PropGetter<"section"> = useCallback(
  (props) =>
    mergeProps(
      {
        id,
        "aria-roledescription": "carousel",
        "data-orientation": orientation,
      },
      rest,
      props,
      { onMouseEnter, onMouseLeave }, // append internal handlers as the last arg so they merge with the consumer's
    )(),
  [id, onMouseEnter, onMouseLeave, rest, orientation],
)
```

Part of the broader cleanup of `PropGetter` callbacks across `packages/react` that currently use raw spread merges instead of `mergeProps`.

### AI used

- [ ] I did not use AI to create this issue.
- [x] (If there is no check above) I checked the generated content before submitting.

### PR DESCRIPTION
**Pull request by hirotomoyamada**
## AI used

- [ ] I did not use AI to create this PR.
- [x] (If there is no check above) I checked the generated content before submitting.

## Description

`useSlider` の `getRootProps` で `mergeProps` を使い、利用者が渡す `className` / `style` / `ref` / イベントがフック側の値と正しくマージされるようにしました。

## Current behavior (updates)

`dataProps`・`rest`・`getRootProps` 引数の `props` を素のスプレッドで結合しており、後勝ちで上書きされていました。

## New behavior

`mergeProps` により `className`・`style`・`ref`・イベントハンドラが既存の `mergeProps` ルールに従ってマージされます。

## Is this a breaking change (Yes/No):

No

## Additional Information

Closes #6832

### CODE REVIEW

File: packages/react/src/components/slider/use-slider.ts [hunk 1]
```diff
@@ -296,14 +297,13 @@ export const useSlider = <Y extends [number, number] | number = number>(
...
     (props = {}) => {
-      const computedProps: HTMLProps = {
-        ...dataProps,
-        "data-orientation": orientation,
-        ...rest,
-        ...props,
-        onBlur: handlerAll(props.onBlur, eventProps.onBlur),
-        onFocus: handlerAll(props.onFocus, eventProps.onFocus),
-      }
+      const computedProps = mergeProps(
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/slider/use-slider.ts]: **Issue:** The PR description and linked issue #6832 frame this as a bug fix ("consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten"). The project rule states "Tests are required: Always write tests when fixing bugs or adding new features." Yet no test was added to `slider.test.tsx`. The change is a real behavior change for hook consumers (e.g., `useSlider({className:"x"}); getRootProps({className:"y"})` now yields `"x y"` via `cx` rather than `"y"` from raw spread), but nothing guards against regressions to the old spread behavior.

**Fix:** Add a test that directly exercises `useSlider` (or renders `Slider.Root` with props flowing through `rest`) and asserts the new merging semantics — at minimum `className` is cx'd, `style` is merged, consumer `onBlur`/`onFocus` runs in addition to the internal field handlers, and `ref` composes with any hook-level ref — so the fix is pinned against future regressions.

Comment (claude-for-yamada-ui) [inline packages/react/src/components/slider/use-slider.ts]: **Issue:** Issue #6832 claims carousel's `getRootProps` "has already been migrated" to `mergeProps`, but `packages/react/src/components/carousel/use-carousel.ts:412-424` still uses the raw-spread + `handlerAll` + `mergeRefs` pattern. A sweep of every other `getRootProps: PropGetter` in `packages/react/src/components/*` (tabs, sidebar, tree, pagination, rating, calendar, radio, radio-group, autocomplete, segmented-control, native-select, carousel, reorder) confirms none uses `mergeProps`. After this PR, `slider` is the sole outlier in the package — the opposite of the "consistency with precedent" framing in the PR/issue. This one-off migration makes the codebase less uniform, not more.

**Fix:** Either revert this PR and migrate all affected getters in a single coordinated change (matching the issue's stated intent of "broader cleanup of `PropGetter` callbacks"), or, at minimum, update the PR description / changeset to explicitly scope this as the first of a series and open tracking issues for the remaining hooks so reviewers can see the migration plan. As-is, the change violates the "one consistent pattern" principle for this file set.

File: packages/react/src/components/slider/use-slider.ts [hunk 2]
```diff
@@ -296,14 +297,13 @@ export const useSlider = <Y extends [number, number] | number = number>(
...
+        dataProps,
+        { "data-orientation": orientation },
+        rest,
+        props,
+        { onBlur: eventProps.onBlur, onFocus: eventProps.onFocus },
+      )() as HTMLProps
```
Comment (claude-for-yamada-ui) [inline packages/react/src/components/slider/use-slider.ts]: **Issue:** The pre-diff code assigned via `const computedProps: HTMLProps = { ... }`, which let TypeScript verify each key against `HTMLProps`. The new code replaces that with `mergeProps(...)() as HTMLProps`, a bare type assertion that silences the type system — mergeProps returns `MergeAll<Args>`, whose shape is unrelated to `HTMLProps`. If any of `dataProps`, `rest`, or `eventProps` later grows a property incompatible with `HTMLProps`, nothing will catch it here. This also conflicts with the project's general stance against `as` casts when a runtime/structural alternative exists.

**Fix:** Drop the `as HTMLProps` cast and instead type the variable at the declaration site (e.g., `const computedProps: HTMLProps = mergeProps(...)()`) so TypeScript checks the merged shape against `HTMLProps`, or narrow the inputs so the inferred return type is already assignable. If `mergeProps`'s generic inference legitimately cannot line up, justify the cast with a comment rather than adding it silently.

**Review by claude-for-yamada-ui — CHANGES_REQUESTED** [review]
- テスト: The PR description and linked issue #6832 frame this as a bug fix ("consumer-supplied `ref`, `className`, `style`, and event handlers passed through the getter are silently overwritten"). The project rule states "Tests are required: Always write tests when fixing bugs or adding new features." Yet no test was added to `slider.test.tsx`. The change is a real behavior change for hook consumers (e.g., `useSlider({className:"x"}); getRootProps({className:"y"})` now yields `"x y"` via `cx` rather than `"y"` from raw spread), but nothing guards against regressions to the old spread behavior.
- 一貫性: Issue #6832 claims carousel's `getRootProps` "has already been migrated" to `mergeProps`, but `packages/react/src/components/carousel/use-carousel.ts:412-424` still uses the raw-spread + `handlerAll` + `mergeRefs` pattern. A sweep of every other `getRootProps: PropGetter` in `packages/react/src/components/*` (tabs, sidebar, tree, pagination, rating, calendar, radio, radio-group, autocomplete, segmented-control, native-select, carousel, reorder) confirms none uses `mergeProps`. After this PR, `slider` is the sole outlier in the package — the opposite of the "consistency with precedent" framing in the PR/issue. This one-off migration makes the codebase less uniform, not more.
- 型安全性: The pre-diff code assigned via `const computedProps: HTMLProps = { ... }`, which let TypeScript verify each key against `HTMLProps`. The new code replaces that with `mergeProps(...)() as HTMLProps`, a bare type assertion that silences the type system — mergeProps returns `MergeAll<Args>`, whose shape is unrelated to `HTMLProps`. If any of `dataProps`, `rest`, or `eventProps` later grows a property incompatible with `HTMLProps`, nothing will catch it here. This also conflicts with the project's general stance against `as` casts when a runtime/structural alternative exists.

File: packages/react/src/components/slider/use-slider.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [inline packages/react/src/components/slider/use-slider.ts]: **Issue:** This changes `getRootProps` merge behavior for consumer props, but the PR adds no regression test. The existing slider tests cover base classes and CSS variables, but not preserving/merging consumer `className`, `style`, or focus/blur handlers through `Slider.Root`/`getRootProps`, so this bug fix can regress unnoticed.

**Fix:** Add a focused slider test that renders `Slider.Root` with consumer props such as `className`, `style`, `onFocus`, and `onBlur`, then asserts the internal root props and consumer props are both preserved/executed.

**Review by codex-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: This changes `getRootProps` merge behavior for consumer props, but the PR adds no regression test. The existing slider tests cover base classes and CSS variables, but not preserving/merging consumer `className`, `style`, or focus/blur handlers through `Slider.Root`/`getRootProps`, so this bug fix can regress unnoticed.

File: packages/react/src/components/slider/use-slider.ts (hunk 2 above)
Comment (composer-for-yamada-ui) [inline packages/react/src/components/slider/use-slider.ts]: **Issue:** The new `mergeProps`-based `getRootProps` path is not covered by any test in this PR. `slider.test.tsx` has no assertions for merged `className`/`style` or chained handlers on the root when overrides are passed into `getRootProps`, even though that is the behavior this change is meant to correct (and Yamada UI rules require tests for fixes).

**Fix:** Add tests (e.g. render via `useSlider` or a minimal wrapper that calls `getRootProps` with extra `className`/`style`/`onBlur`) asserting `cx`-style class merging, merged `style`, and that both consumer and internal blur/focus handlers run. Place them in `packages/react/src/components/slider/slider.test.tsx` or a dedicated `use-slider` test file.

**Review by composer-for-yamada-ui — CHANGES_REQUESTED** [review]
- Tests: The new `mergeProps`-based `getRootProps` path is not covered by any test in this PR. `slider.test.tsx` has no assertions for merged `className`/`style` or chained handlers on the root when overrides are passed into `getRootProps`, even though that is the behavior this change is meant to correct (and Yamada UI rules require tests for fixes).

File: packages/react/src/components/slider/use-slider.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/slider/use-slider.ts]: Fixed.

File: packages/react/src/components/slider/use-slider.ts (hunk 1 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/slider/use-slider.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/slider/use-slider.ts]: Fixed.

Comment (codex-for-yamada-ui) [reply packages/react/src/components/slider/use-slider.ts]: Fixed.

File: packages/react/src/components/slider/use-slider.ts (hunk 2 above)
Comment (codex-for-yamada-ui) [reply packages/react/src/components/slider/use-slider.ts]: Fixed.

**Review by claude-for-yamada-ui — APPROVED** [review]

**Review by codex-for-yamada-ui — APPROVED** [review]

**Review by composer-for-yamada-ui — APPROVED** [review]
